/**
 * Catálogo de produtos, soluções e integrações em português do Brasil.
 * Mesma forma e ordem do texto base em español (lib/catalog).
 */
import type { CatalogText } from '../types'

export const catalog: CatalogText = {
  categories: {
    operacion: { name: 'Operação', text: 'O que acontece no caixa, no estoque e nos quartos.' },
    finanzas: { name: 'Finanças e equipe', text: 'Notas fiscais, contas e folha de pagamento em dia.' },
    clientes: { name: 'Clientes', text: 'Cada conversa e cada venda em um só histórico.' },
    canales: { name: 'Canais digitais', text: 'Seu negócio na internet desde o primeiro dia.' },
    inteligencia: { name: 'Informação e IA', text: 'Respostas claras para decidir.' },
  },

  products: {
    // -----------------------------------------------------------------------
    // Operação
    // -----------------------------------------------------------------------
    'ventas-pos': {
      name: 'Vendas e PDV',
      short: 'Caixa, mesas, comandas e pagamentos.',
      eyebrow: 'Vendas e PDV',
      headline: 'Receba sem filas e sem caderninho.',
      lead: 'Um PDV para loja, restaurante ou academia. Cada venda baixa o estoque, fica pronta para faturar e aparece nos seus relatórios.',
      pains: [
        { pain: 'No fechamento, o caixa não bate e você não sabe por quê.', answer: 'Conferência por forma de pagamento e diferenças explicadas no fechamento.' },
        { pain: 'Os pedidos das mesas se perdem entre o bar e a cozinha.', answer: 'Comandas que chegam à cozinha por estação, com status em tempo real.' },
        { pain: 'Você vende algo que já não tem no estoque.', answer: 'O estoque baixa a cada venda e avisa antes de acabar.' },
      ],
      features: [
        { title: 'Abertura e fechamento de caixa', text: 'Fundo de troco, movimentações, conferência e contagem por cédula e moeda.' },
        { title: 'Mesas e comandas', text: 'Mapa de mesas por área, contas divididas, gorjetas e taxa de serviço.' },
        { title: 'Todas as formas de pagamento', text: 'Dinheiro, cartão, transferência e pagamento por QR na mesma venda.' },
        { title: 'Promoções e cupons', text: 'Regras de desconto, cupons e preços por tabela ou por filial.' },
        { title: 'Devoluções organizadas', text: 'Motivos de devolução, nota de crédito e retorno ao estoque.' },
        { title: 'Impressoras e terminais', text: 'Cupons, comandas por estação e vários caixas por filial.' },
      ],
      steps: [
        { title: 'Abra o caixa', text: 'Registre o fundo de troco e quem está atendendo.' },
        { title: 'Venda', text: 'Busque por nome ou código de barras e receba com uma ou mais formas de pagamento.' },
        { title: 'Fature', text: 'Emita a nota fiscal ou o cupom na própria venda.' },
        { title: 'Feche', text: 'A conferência compara o que foi contado com o que foi vendido.' },
      ],
      highlights: ['Vendas por filial e por operador de caixa', 'Comandas para cozinha e bar', 'Faturamento no mesmo fluxo'],
      faq: [
        { q: 'Funciona em tablet ou celular?', a: 'Sim. O GO Admin funciona no navegador do computador, do tablet ou do celular.' },
        { q: 'Posso ter vários caixas na mesma filial?', a: 'Sim. Cada caixa tem sua abertura, suas movimentações e seu fechamento.' },
        { q: 'Conecta com impressoras de cupons e comandas?', a: 'Sim. Você define impressoras por estação para que cada área receba o que é dela.' },
      ],
    },
    inventario: {
      name: 'Estoque',
      short: 'Estoque por depósito, lotes e transferências.',
      eyebrow: 'Estoque',
      headline: 'Saiba o que você tem e onde está.',
      lead: 'Saldos por depósito e filial, custos, lotes e transferências. Cada venda baixa e cada compra soma, sem planilhas.',
      pains: [
        { pain: 'Você conta o estoque e nunca bate com o sistema.', answer: 'Inventários rotativos, ajustes com motivo e kardex de cada movimentação.' },
        { pain: 'Você não sabe quanto realmente custa o que vende.', answer: 'Custo médio e PEPS atualizados a cada compra.' },
        { pain: 'Você transfere mercadoria entre filiais e perde o rastro.', answer: 'Transferências com saída, trânsito e recebimento com diferenças.' },
      ],
      features: [
        { title: 'Catálogo completo', text: 'Categorias em árvore, variações (tamanho, cor), imagens, unidades e códigos de barras.' },
        { title: 'Estoque em tempo real', text: 'Saldos por depósito e filial com alertas de estoque mínimo.' },
        { title: 'Compras e fornecedores', text: 'Pedidos de compra, recebimento e ligação com contas a pagar.' },
        { title: 'Lotes e números de série', text: 'Validades, garantias e rastreabilidade por número de série.' },
        { title: 'Fichas técnicas e produção', text: 'Baixa os ingredientes quando você vende um prato ou produz um lote.' },
        { title: 'Kardex e ajustes', text: 'Histórico de cada movimentação com quem, quando e por quê.' },
      ],
      steps: [
        { title: 'Importe seu catálogo', text: 'Suba produtos e saldos a partir do Excel.' },
        { title: 'Defina depósitos e mínimos', text: 'Por filial e por produto.' },
        { title: 'Opere', text: 'Vendas, compras e transferências movimentam o estoque sozinhas.' },
        { title: 'Conte e ajuste', text: 'Inventários rotativos com diferenças explicadas.' },
      ],
      highlights: ['Vários depósitos e filiais', 'Variações e códigos de barras', 'Custo médio e PEPS'],
      faq: [
        { q: 'Posso controlar tamanhos e cores?', a: 'Sim. Você cria tipos de variação e cada combinação tem seu próprio estoque e código.' },
        { q: 'Serve para restaurantes?', a: 'Sim. Com fichas técnicas, cada prato vendido baixa seus ingredientes.' },
        { q: 'Como carrego meu estoque inicial?', a: 'Você importa do Excel e nós acompanhamos a primeira carga.' },
      ],
    },
    hoteleria: {
      name: 'Hotelaria (PMS)',
      short: 'Reservas, check-in, folios e canais.',
      eyebrow: 'Hotelaria',
      headline: 'Reservas e quartos sem conflitos.',
      lead: 'Calendário de ocupação, check-in e check-out, folios por hóspede, tarifas e conexão com canais como Booking.com e Expedia.',
      pains: [
        { pain: 'Um quarto vendido duas vezes em canais diferentes.', answer: 'Disponibilidade sincronizada com os canais de reserva.' },
        { pain: 'Os consumos do hóspede ficam no papel.', answer: 'Folios com lançamentos do restaurante, frigobar e serviços.' },
        { pain: 'A governança não sabe quais quartos limpar primeiro.', answer: 'Tarefas de limpeza e manutenção conforme saídas e chegadas.' },
      ],
      features: [
        { title: 'Calendário de reservas', text: 'Visão por tipo de quarto, bloqueios e grupos.' },
        { title: 'Check-in e check-out', text: 'Registro de hóspedes e saída com folio fechado.' },
        { title: 'Folios com várias contas', text: 'Lançamentos separados por hóspede ou empresa.' },
        { title: 'Tarifas e extras', text: 'Tarifas por temporada, pacotes e serviços adicionais.' },
        { title: 'Channel manager', text: 'Booking.com, Expedia, Airbnb e calendários iCal.' },
        { title: 'Governança', text: 'Tarefas de limpeza e ordens de manutenção.' },
      ],
      steps: [
        { title: 'Configure os quartos', text: 'Tipos, unidades, tarifas e serviços.' },
        { title: 'Conecte os canais', text: 'Mapeie seus tipos de quarto em cada canal.' },
        { title: 'Receba reservas', text: 'Dos canais, do seu motor de reservas ou da recepção.' },
        { title: 'Fature a estadia', text: 'O folio vira nota fiscal no check-out.' },
      ],
      highlights: ['Motor de reservas próprio', 'Booking.com e Expedia', 'Folios e faturamento'],
      faq: [
        { q: 'Conecta com o Booking.com?', a: 'Sim. Você mapeia seus tipos de quarto e tarifas, e as reservas chegam ao calendário.' },
        { q: 'Posso lançar consumos do restaurante no quarto?', a: 'Sim. Os lançamentos do PDV podem ir para o folio do hóspede.' },
      ],
    },

    // -----------------------------------------------------------------------
    // Finanças e equipe
    // -----------------------------------------------------------------------
    'facturacion-electronica': {
      name: '{invoicing}',
      short: 'Notas fiscais autorizadas por {theAuthority} na própria venda.',
      eyebrow: '{invoicing}',
      headline: 'Emita nota fiscal sem sair de onde você vende.',
      lead: 'Emita notas fiscais, notas de crédito e documentos de suporte validados por {theAuthority} no PDV ou no financeiro, e consulte o status de cada um em um só lugar.',
      pains: [
        { pain: 'Você emite notas em outro programa e digita tudo duas vezes.', answer: 'A nota sai da venda, com cliente, produtos e impostos.' },
        { pain: 'Você não sabe se {theAuthority} aceitou ou rejeitou um documento.', answer: 'Status de cada documento, com o erro explicado quando houver.' },
        { pain: 'Notas de crédito e devoluções viram uma confusão.', answer: 'Nota de crédito ligada à nota fiscal e à devolução.' },
      ],
      features: [
        { title: 'Nota fiscal de venda', text: 'Numeração, autorizações e envio ao cliente por e-mail.' },
        { title: 'Notas de crédito e débito', text: 'Ligadas à nota original e às devoluções.' },
        { title: 'Documento de suporte', text: 'Para compras de fornecedores não obrigados a emitir nota fiscal.' },
        { title: 'Impostos e retenções', text: '{taxes} configuráveis por produto e cliente.' },
        { title: 'Status junto a {theAuthority}', text: '{docId}, QR code e resposta de validação de cada documento.' },
        { title: 'Consulta de clientes', text: 'Dados fiscais do cliente para evitar erros.' },
      ],
      steps: [
        { title: 'Habilite-se', text: 'Configure sua autorização e seu certificado digital.' },
        { title: 'Venda', text: 'Pelo PDV, por um orçamento ou pelo financeiro.' },
        { title: 'Emita', text: 'O documento é validado e enviado ao cliente.' },
        { title: 'Consulte', text: 'Status, PDF e XML sempre à mão.' },
      ],
      highlights: ['Incluída em todos os planos', 'Nota fiscal, notas de crédito e documento de suporte', 'Status junto a {theAuthority} em tempo real'],
      faq: [
        { q: 'Preciso de um certificado digital?', a: 'Sim, para assinar os documentos. Se você não tiver, pode adquiri-lo como complemento.' },
        { q: 'Posso emitir nota pelo celular?', a: 'Sim. O faturamento funciona no navegador de qualquer dispositivo.' },
      ],
      variants: {
        noEInvoice: {
          short: 'Notas fiscais com os impostos do seu país.',
          lead: 'Emita notas fiscais e notas de crédito com {taxes}, no PDV ou no financeiro, e envie ao seu cliente. {einvoiceNote}',
          pains: [
            { pain: 'Você emite notas em outro programa e digita tudo duas vezes.', answer: 'A nota sai da venda, com cliente, produtos e impostos.' },
            { pain: 'Você calcula os impostos à mão em cada nota.', answer: '{taxes} configurados por produto e cliente.' },
            { pain: 'Notas de crédito e devoluções viram uma confusão.', answer: 'Nota de crédito ligada à nota fiscal e à devolução.' },
          ],
          features: [
            { title: 'Nota fiscal de venda', text: 'Numeração, PDF e envio ao cliente por e-mail.' },
            { title: 'Notas de crédito e débito', text: 'Ligadas à nota original e às devoluções.' },
            { title: 'Várias moedas', text: 'Notas na sua moeda e em outras, com taxa de câmbio.' },
            { title: 'Impostos do seu país', text: '{taxes} configuráveis por produto e cliente.' },
            { title: 'Dados fiscais', text: 'Identificação dos seus clientes com {taxId} e os documentos do seu país.' },
            { title: 'Consulta de clientes', text: 'Histórico de notas, pagamentos e saldos por cliente.' },
          ],
          steps: [
            { title: 'Configure', text: 'Numeração, impostos e dados da sua empresa.' },
            { title: 'Venda', text: 'Pelo PDV, por um orçamento ou pelo financeiro.' },
            { title: 'Emita', text: 'O documento é gerado e enviado ao cliente.' },
            { title: 'Consulte', text: 'Status, PDF e pagamentos sempre à mão.' },
          ],
          highlights: ['Impostos do seu país configurados', 'Notas fiscais e notas de crédito', 'Conectada com vendas e contabilidade'],
          faq: [
            { q: 'Como funciona a nota fiscal eletrônica {inCountry}?', a: '{einvoiceNote}' },
            { q: 'Posso emitir nota pelo celular?', a: 'Sim. O faturamento funciona no navegador de qualquer dispositivo.' },
          ],
        },
      },
    },
    contabilidad: {
      name: 'Contabilidade e finanças',
      short: 'Lançamentos, contas a receber, bancos e fechamentos.',
      eyebrow: 'Contabilidade',
      headline: 'Contas claras sem digitar de novo.',
      lead: 'Cada venda, compra e pagamento gera seu lançamento. Contas a receber, contas a pagar, bancos, conciliação e fechamentos no mesmo sistema em que você opera.',
      pains: [
        { pain: 'Seu contador recebe as informações tarde e em arquivos soltos.', answer: 'Lançamentos automáticos a partir da operação, prontos para revisar.' },
        { pain: 'Você não sabe quem te deve nem a quem você deve.', answer: 'Contas a receber e a pagar com parcelas e lembretes.' },
        { pain: 'Conciliar o banco leva dias.', answer: 'Conciliação com os extratos importados do banco.' },
      ],
      features: [
        { title: 'Plano de contas', text: 'Baseado no {chart}, com regras contábeis configuráveis.' },
        { title: 'Lançamentos automáticos', text: 'Vendas, compras, pagamentos e folha contabilizam sozinhos.' },
        { title: 'Contas a receber e a pagar', text: 'Parcelas, vencimentos e lembretes de cobrança.' },
        { title: 'Bancos e conciliação', text: 'Contas bancárias, transferências e conciliação bancária.' },
        { title: 'Centros de custo e orçamentos', text: 'Resultados por filial, área ou projeto.' },
        { title: 'Ativo imobilizado e fechamentos', text: 'Depreciações e períodos fiscais.' },
      ],
      steps: [
        { title: 'Configure', text: 'Plano de contas, impostos e regras contábeis.' },
        { title: 'Opere', text: 'Cada documento gera seu lançamento.' },
        { title: 'Concilie', text: 'Cruze bancos, contas a receber e pagamentos.' },
        { title: 'Feche o mês', text: 'Revise, ajuste e bloqueie o período.' },
      ],
      highlights: ['Plano de contas e regras contábeis', 'Conciliação bancária', 'Centros de custo e orçamentos'],
      faq: [
        { q: 'Meu contador pode trabalhar no GO Admin?', a: 'Sim. Você cria um usuário para ele com o perfil e as permissões de que precisa.' },
        { q: 'O que acontece se um lançamento falhar?', a: 'Ele fica registrado para você revisar e corrigir, sem perder o documento de origem.' },
      ],
    },
    nomina: {
      name: 'Folha de pagamento e equipe',
      short: 'Contratos, escalas e folha de pagamento eletrônica.',
      eyebrow: 'Folha de pagamento e equipe',
      headline: 'Sua equipe em ordem.',
      lead: 'Funcionários, contratos, escalas, ponto, férias, empréstimos e folha de pagamento em um só lugar, conectados com a contabilidade.',
      pains: [
        { pain: 'As escalas vivem em um grupo de WhatsApp.', answer: 'Modelos de escala e rodízios visíveis para todos.' },
        { pain: 'Fechar a folha leva um dia inteiro.', answer: 'Períodos, eventos e holerites calculados.' },
        { pain: 'Você não sabe quantos dias de férias cada pessoa ainda tem.', answer: 'Saldos de férias e licenças atualizados.' },
      ],
      features: [
        { title: 'Funcionários e contratos', text: 'Cargos, áreas, salários e documentos.' },
        { title: 'Escalas e rodízios', text: 'Modelos e atribuições por filial.' },
        { title: 'Ponto', text: 'Registros de entrada e saída e folhas de horas.' },
        { title: 'Férias e licenças', text: 'Solicitações, aprovações e saldos.' },
        { title: 'Folha de pagamento', text: 'Períodos, eventos, holerites e folha eletrônica junto a {theAuthority}.' },
        { title: 'Empréstimos e adiantamentos', text: 'Parcelas descontadas em cada período.' },
      ],
      steps: [
        { title: 'Cadastre sua equipe', text: 'Dados, contrato e salário.' },
        { title: 'Monte as escalas', text: 'Modelos e rodízios por filial.' },
        { title: 'Registre os eventos', text: 'Horas extras, faltas e férias.' },
        { title: 'Feche a folha', text: 'Holerites e lançamentos contábeis.' },
      ],
      highlights: ['Escalas e ponto', 'Férias e licenças', 'Folha conectada com a contabilidade'],
      faq: [
        { q: 'Os funcionários podem ver suas escalas?', a: 'Sim, com um usuário e as permissões que você definir para o cargo.' },
        { q: 'A folha gera os lançamentos contábeis?', a: 'Sim. Cada fechamento da folha fica contabilizado.' },
      ],
      variants: {
        noEPayroll: {
          short: 'Contratos, escalas e cálculo da folha de pagamento.',
          features: [
            { title: 'Funcionários e contratos', text: 'Cargos, áreas, salários e documentos.' },
            { title: 'Escalas e rodízios', text: 'Modelos e atribuições por filial.' },
            { title: 'Ponto', text: 'Registros de entrada e saída e folhas de horas.' },
            { title: 'Férias e licenças', text: 'Solicitações, aprovações e saldos.' },
            { title: 'Folha de pagamento', text: 'Períodos, eventos e holerites com as regras trabalhistas do seu país.' },
            { title: 'Empréstimos e adiantamentos', text: 'Parcelas descontadas em cada período.' },
          ],
        },
      },
    },

    // -----------------------------------------------------------------------
    // Clientes
    // -----------------------------------------------------------------------
    'clientes-crm': {
      name: 'Clientes (CRM)',
      short: 'Histórico, oportunidades e campanhas.',
      eyebrow: 'Clientes e CRM',
      headline: 'Lembre-se de cada cliente.',
      lead: 'A ficha de cada cliente reúne compras, reservas, conversas e tarefas. Oportunidades em funis, acompanhamentos e campanhas por segmento.',
      pains: [
        { pain: 'As informações do cliente estão na cabeça de um vendedor.', answer: 'Ficha 360° com todo o histórico do cliente.' },
        { pain: 'Os orçamentos esfriam sem acompanhamento.', answer: 'Funis com etapas, tarefas e lembretes.' },
        { pain: 'Você manda a mesma promoção para todo mundo.', answer: 'Segmentos e campanhas de acordo com o que cada cliente compra.' },
      ],
      features: [
        { title: 'Ficha 360°', text: 'Compras, notas fiscais, reservas, anotações e conversas.' },
        { title: 'Funis de vendas', text: 'Etapas personalizáveis, oportunidades e orçamentos.' },
        { title: 'Tarefas e atividades', text: 'Ligações, reuniões e lembretes por responsável.' },
        { title: 'Segmentos e campanhas', text: 'Por e-mail, WhatsApp ou SMS.' },
        { title: 'Automações', text: 'Ações disparadas por eventos do negócio.' },
        { title: 'Consentimentos', text: 'Preferências de contato de cada cliente.' },
      ],
      steps: [
        { title: 'Reúna seus clientes', text: 'Importe sua base ou cadastre na hora da venda.' },
        { title: 'Organize o funil', text: 'Defina etapas de acordo com a forma como você vende.' },
        { title: 'Acompanhe', text: 'Tarefas e lembretes para cada oportunidade.' },
        { title: 'Comunique', text: 'Campanhas por segmento e automações.' },
      ],
      highlights: ['Ficha 360°', 'Funis e orçamentos', 'Campanhas por WhatsApp e e-mail'],
      faq: [
        { q: 'Posso importar meus clientes atuais?', a: 'Sim, do Excel. Eles também são criados ao vender ou reservar.' },
        { q: 'As campanhas saem pelo WhatsApp?', a: 'Sim, conectando seu WhatsApp Business. Também por e-mail e SMS.' },
      ],
    },
    'chat-omnicanal': {
      name: 'Chat omnichannel',
      short: 'WhatsApp, Instagram e site em uma só caixa de entrada.',
      eyebrow: 'Chat omnichannel',
      headline: 'Todas as conversas em uma só caixa de entrada.',
      lead: 'WhatsApp, Instagram, Facebook e o chat do seu site chegam ao mesmo lugar. Distribua as conversas para a equipe e deixe um assistente com IA responder o que é frequente.',
      pains: [
        { pain: 'Você responde em três celulares diferentes.', answer: 'Uma caixa de entrada compartilhada para todos os canais.' },
        { pain: 'As mesmas perguntas tomam o seu dia.', answer: 'Respostas rápidas e um assistente com IA treinado com as suas informações.' },
        { pain: 'Você não sabe quem atendeu quem.', answer: 'Atribuições, status e notas internas em cada conversa.' },
      ],
      features: [
        { title: 'Caixa de entrada unificada', text: 'WhatsApp, Instagram, Facebook e chat do site.' },
        { title: 'Atribuição e status', text: 'Por atendente ou departamento, com histórico.' },
        { title: 'Assistente com IA', text: 'Responde com seu catálogo, horários e políticas.' },
        { title: 'Respostas rápidas', text: 'Modelos para as perguntas de sempre.' },
        { title: 'Widget para o seu site', text: 'Chat no seu site do GO Admin ou em outro.' },
        { title: 'Resumo e etiquetas', text: 'Resumos automáticos e etiquetas por assunto.' },
      ],
      steps: [
        { title: 'Conecte seus canais', text: 'WhatsApp Business, Instagram e seu site.' },
        { title: 'Treine o assistente', text: 'Com seus produtos, preços e perguntas frequentes.' },
        { title: 'Atenda em equipe', text: 'Atribua, responda e deixe notas.' },
        { title: 'Venda', text: 'A conversa fica na ficha do cliente.' },
      ],
      highlights: ['WhatsApp, Instagram e site', 'Assistente treinado com as suas informações', 'Histórico no CRM'],
      faq: [
        { q: 'O assistente responde sozinho?', a: 'Ele responde o que é frequente com as informações que você fornece; sua equipe pode assumir a conversa a qualquer momento.' },
        { q: 'Preciso do WhatsApp Business?', a: 'Sim, para conectar o WhatsApp à caixa de entrada compartilhada.' },
      ],
    },

    // -----------------------------------------------------------------------
    // Canais digitais
    // -----------------------------------------------------------------------
    'sitio-web': {
      name: 'Site',
      short: 'Seu site com domínio próprio, pronto em minutos.',
      eyebrow: 'Site',
      headline: 'Seu negócio na internet desde o primeiro dia.',
      lead: 'Cada organização recebe seu site em um endereço do GO Admin ou com domínio próprio. Você escolhe um modelo, ajusta com a sua marca e ele se atualiza sozinho com seus produtos, serviços e horários.',
      pains: [
        { pain: 'Ter um site significava contratar alguém e esperar.', answer: 'Modelos por segmento prontos para publicar.' },
        { pain: 'O site fica desatualizado, com preços antigos.', answer: 'Produtos, preços e horários vêm do ERP.' },
        { pain: 'Ninguém encontra você no Google.', answer: 'Título, descrição e imagem para buscadores e redes em cada página.' },
      ],
      features: [
        { title: 'Modelos por segmento', text: 'Moderno, clássico, elegante, restaurante, hotel, loja e estacionamento.' },
        { title: 'Construtor de páginas', text: 'Seções que você organiza e edita, com rascunho e publicação.' },
        { title: 'Domínio próprio', text: 'Subdomínio do GO Admin ou seu domínio, com verificação e certificado.' },
        { title: 'Sua marca', text: 'Logo, cores, fontes, menus e rodapé.' },
        { title: 'Buscadores e redes', text: 'Metadados, imagem para compartilhamento e verificação do Google.' },
        { title: 'Visitas e avaliações', text: 'Estatísticas de visitas e avaliações de clientes moderadas.' },
      ],
      steps: [
        { title: 'Escolha um modelo', text: 'De acordo com o seu segmento.' },
        { title: 'Coloque a sua marca', text: 'Logo, cores e conteúdo.' },
        { title: 'Conecte seu domínio', text: 'Ou use o endereço do GO Admin.' },
        { title: 'Publique', text: 'Seus produtos e horários se atualizam sozinhos.' },
      ],
      highlights: ['Subdomínio incluído ou domínio próprio', 'Modelos por segmento', 'Conteúdo conectado ao ERP'],
      faq: [
        { q: 'Posso usar meu próprio domínio?', a: 'Sim. Você conecta seu domínio com uma verificação de DNS; também pode comprá-lo pelo GO Admin.' },
        { q: 'Preciso saber programar?', a: 'Não. Você edita seções, textos e imagens no construtor.' },
        { q: 'O que acontece se eu mudar um preço?', a: 'Ele se atualiza no seu site, porque vem do mesmo catálogo.' },
      ],
    },
    'tienda-en-linea': {
      name: 'Loja virtual',
      short: 'Venda pela internet com o seu estoque real.',
      eyebrow: 'Loja virtual',
      headline: 'Venda on-line com o estoque que você já tem.',
      lead: 'Seu catálogo publicado como loja: carrinho, pagamentos on-line, entrega ou retirada, cupons e avaliações. Cada pedido chega ao GO Admin, baixa o estoque e fica pronto para faturar.',
      pains: [
        { pain: 'Você controla a loja virtual e o estoque separadamente.', answer: 'O estoque é o mesmo para a loja física e a virtual.' },
        { pain: 'Os pedidos chegam pelo WhatsApp e se perdem.', answer: 'Cada pedido tem número, status e responsável.' },
        { pain: 'Receber on-line parece complicado.', answer: 'Meios de pagamento do seu país já conectados.' },
      ],
      features: [
        { title: 'Catálogo publicado', text: 'Categorias, variações, fotos e preços vindos do estoque.' },
        { title: 'Carrinho e pagamentos', text: '{gateways} e outros.' },
        { title: 'Entrega ou retirada', text: 'Tarifas de frete, frete grátis a partir de um valor e pedidos agendados.' },
        { title: 'Cupons e promoções', text: 'Códigos de desconto e contagens regressivas.' },
        { title: 'Pedidos em tempo real', text: 'Confirmação, preparo, despacho e entrega.' },
        { title: 'Avaliações de clientes', text: 'Notas verificadas por compra, com resposta.' },
      ],
      steps: [
        { title: 'Ative a loja', text: 'Seu catálogo já está carregado.' },
        { title: 'Conecte os pagamentos', text: 'Escolha seu meio de pagamento.' },
        { title: 'Defina as entregas', text: 'Entrega, retirada e tarifas.' },
        { title: 'Receba pedidos', text: 'Eles chegam ao ERP com seu status.' },
      ],
      highlights: ['Mesmo estoque da loja física', 'Pagamentos on-line {inCountry}', 'Entrega, retirada e cupons'],
      faq: [
        { q: 'Quais meios de pagamento posso usar?', a: '{gateways}, entre outros.' },
        { q: 'Serve para pedidos de restaurante?', a: 'Sim. Com entrega ou retirada, gorjetas e pedidos agendados.' },
      ],
    },
    'motor-de-reservas': {
      name: 'Motor de reservas',
      short: 'Reservas diretas de quartos, mesas e horários.',
      eyebrow: 'Motor de reservas',
      headline: 'Reservas diretas, sem comissão de intermediários.',
      lead: 'Seus clientes reservam quartos, mesas ou horários pelo seu site, com disponibilidade real. As reservas chegam ao calendário do GO Admin junto com as dos canais externos.',
      pains: [
        { pain: 'Você depende de plataformas que cobram comissão por cada reserva.', answer: 'Reservas diretas pelo seu próprio site.' },
        { pain: 'Você confirma as reservas uma a uma por telefone.', answer: 'Confirmação automática por e-mail ou WhatsApp.' },
        { pain: 'Os clientes não aparecem e você perde a mesa.', answer: 'Lembretes, políticas de cancelamento e depósitos.' },
      ],
      features: [
        { title: 'Quartos', text: 'Disponibilidade e tarifas do PMS, com extras.' },
        { title: 'Mesas', text: 'Turnos, tamanho do grupo, áreas e atribuição de mesa.' },
        { title: 'Agendamentos e aulas', text: 'Agenda de serviços, aulas e planos.' },
        { title: 'Depósitos e políticas', text: 'Sinal, cancelamento e confirmação.' },
        { title: 'Lembretes', text: 'Por e-mail e WhatsApp antes da chegada.' },
        { title: 'Tudo em um calendário', text: 'Diretas e de canais externos, sem conflitos.' },
      ],
      steps: [
        { title: 'Defina a disponibilidade', text: 'Quartos, mesas ou serviços.' },
        { title: 'Configure as regras', text: 'Antecedência, grupos, depósitos.' },
        { title: 'Publique', text: 'No seu site do GO Admin.' },
        { title: 'Receba', text: 'Reservas confirmadas no seu calendário.' },
      ],
      highlights: ['Quartos, mesas e agendamentos', 'Depósitos e lembretes', 'Mesmo calendário dos seus canais'],
      faq: [
        { q: 'Funciona junto com o Booking.com?', a: 'Sim. As reservas diretas e as dos canais compartilham o mesmo calendário.' },
        { q: 'Posso pedir um depósito?', a: 'Sim. Você define se é fixo ou por pessoa.' },
      ],
    },

    // -----------------------------------------------------------------------
    // Informação e IA
    // -----------------------------------------------------------------------
    reportes: {
      name: 'Relatórios',
      short: 'Painéis prontos para decidir.',
      eyebrow: 'Relatórios e análises',
      headline: 'Você vendeu mais ou lucrou mais?',
      lead: 'Painéis de vendas, margens, contas a receber, estoque e equipe prontos desde o primeiro dia. Salve suas visões e receba relatórios agendados no seu e-mail.',
      pains: [
        { pain: 'Você monta relatórios no Excel todo fim de mês.', answer: 'Painéis que se atualizam a cada operação.' },
        { pain: 'Você vê as vendas, mas não a margem.', answer: 'Vendas, custo e margem por produto e filial.' },
        { pain: 'Você fica sabendo tarde do que importa.', answer: 'Alertas quando um indicador passa de um limite.' },
      ],
      features: [
        { title: 'Painéis por área', text: 'Vendas, estoque, finanças, clientes e equipe.' },
        { title: 'Comparativos', text: 'Por período, filial, vendedor ou canal.' },
        { title: 'Relatórios salvos', text: 'Seus filtros e colunas, prontos para repetir.' },
        { title: 'Envios agendados', text: 'No seu e-mail todo dia, semana ou mês.' },
        { title: 'Alertas', text: 'Quando algo precisa da sua atenção.' },
        { title: 'Exporte', text: 'Para Excel e PDF.' },
      ],
      steps: [
        { title: 'Abra seu painel', text: 'Ele já vem montado.' },
        { title: 'Filtre', text: 'Por data, filial ou canal.' },
        { title: 'Salve', text: 'Suas visões favoritas.' },
        { title: 'Agende', text: 'Receba o relatório sem precisar pedir.' },
      ],
      highlights: ['Painéis prontos', 'Relatórios agendados', 'Alertas por indicador'],
      faq: [
        { q: 'Posso ver várias filiais juntas?', a: 'Sim, e também compará-las entre si.' },
        { q: 'Quem pode ver os relatórios?', a: 'Você define por perfil: cada pessoa vê o que lhe cabe.' },
      ],
    },
    'inteligencia-artificial': {
      name: 'GO Admin IA',
      short: 'Pergunte ao seu negócio.',
      eyebrow: 'GO Admin IA',
      headline: 'Pergunte ao seu negócio.',
      lead: 'Escreva como você falaria com o seu contador. A IA consulta suas vendas, seu estoque e suas contas a receber e responde com números e gráficos. Ela também ajuda com textos e imagens para os seus produtos.',
      pains: [
        { pain: 'Você tem dados, mas não tem tempo para analisá-los.', answer: 'Perguntas em linguagem natural e respostas com números.' },
        { pain: 'Escrever descrições de produtos leva horas.', answer: 'Textos e imagens gerados a partir do seu catálogo.' },
        { pain: 'As dúvidas contábeis ficam esperando o contador.', answer: 'Assistente contábil que explica e sugere lançamentos.' },
      ],
      features: [
        { title: 'Pergunte com suas palavras', text: '"O que mais vendeu esta semana?" e receba a resposta.' },
        { title: 'Relatórios a partir de uma pergunta', text: 'Com tabela e gráfico prontos para compartilhar.' },
        { title: 'Assistente contábil', text: 'Explicações e sugestões sobre suas movimentações.' },
        { title: 'Conteúdo para produtos', text: 'Descrições e imagens para a sua loja.' },
        { title: 'Agentes que sugerem', text: 'Recomendações de reposição e de cobrança.' },
        { title: 'Créditos por plano', text: '500, 2.000 ou 10.000 créditos por mês, com recargas.' },
      ],
      steps: [
        { title: 'Abra o assistente', text: 'De qualquer tela.' },
        { title: 'Pergunte', text: 'Como você falaria com uma pessoa.' },
        { title: 'Revise', text: 'Números, tabela e gráfico.' },
        { title: 'Aja', text: 'Salve o relatório ou crie a tarefa.' },
      ],
      highlights: ['Respostas com os seus dados', 'Assistente contábil', 'Textos e imagens para produtos'],
      faq: [
        { q: 'A IA vê dados de outros negócios?', a: 'Não. Ela consulta somente as informações da sua organização e respeita as permissões de cada usuário.' },
        { q: 'O que são os créditos de IA?', a: 'Cada consulta ou geração consome créditos. Cada plano inclui uma quantidade mensal e você pode comprar mais.' },
      ],
    },
  },

  solutions: {
    gastronomia: {
      name: 'Restaurantes, bares e cafés',
      short: 'Tudo o que serve comida e bebida: mesas, balcão, bar e delivery.',
      types: [
        'Restaurantes',
        'Lanchonetes',
        'Bares e botecos',
        'Casas noturnas',
        'Cafeterias',
        'Padarias e confeitarias',
        'Sorveterias',
        'Food trucks',
        'Dark kitchens',
        'Bufês e eventos',
        'Refeitórios e restaurantes corporativos',
      ],
      headline: 'Do pedido à cozinha, sem papelzinho.',
      lead: 'Mesas, bar ou balcão; comandas que chegam a cada estação, fichas técnicas que baixam os ingredientes e um caixa que bate. Com cardápio on-line, pedidos para entrega e reservas pelo seu site.',
      pains: [
        { pain: 'As comandas se perdem entre o bar e a cozinha.', answer: 'Comandas por estação com status na tela ou na impressora.' },
        { pain: 'Você não sabe quanto custa cada prato ou cada drinque.', answer: 'Fichas técnicas que baixam os ingredientes e calculam o custo.' },
        { pain: 'Os pedidos chegam pelo WhatsApp, por apps e por telefone.', answer: 'Pedidos da sua loja virtual e dos apps de delivery em um só lugar.' },
        { pain: 'As contas abertas viram confusão no fim do turno.', answer: 'Contas por mesa ou por pessoa, divisíveis na hora de pagar.' },
      ],
      day: [
        { moment: 'Antes de abrir', title: 'Você confere insumos e produção', text: 'Alertas do que está acabando e ordens de produção para a cozinha ou o forno.' },
        { moment: 'Horário de pico', title: 'Mesas, bar e balcão', text: 'Recebimentos rápidos, contas divididas, gorjetas e comandas para cada estação.' },
        { moment: 'O dia todo', title: 'Pedidos on-line', text: 'Entregas e pedidos para retirada pela sua loja, com status e responsável.' },
        { moment: 'No fechamento', title: 'Você fecha o dia', text: 'Conferência de caixa, vendas por garçom ou operador, perdas e notas emitidas.' },
      ],
      channel: { title: 'Seu cardápio on-line, com pedidos e reservas', text: 'Publique seu cardápio com fotos e receba pedidos para entrega ou retirada e reservas de mesa pelo seu site.' },
      features: [
        { title: 'Mesas, bar ou balcão', text: 'Mapa de mesas por área, contas abertas ou venda rápida.' },
        { title: 'Modificadores', text: 'Ponto da carne, adicionais e retirada de ingredientes em cada produto.' },
        { title: 'Fichas técnicas e produção', text: 'Custo por prato ou por drinque e baixa de ingredientes.' },
        { title: 'Gorjetas e taxas', text: 'Gorjeta sugerida, taxa de serviço e couvert.' },
        { title: 'Vários caixas e estações', text: 'Cozinha, bar, sobremesas ou vários pontos de venda.' },
        { title: 'Perdas', text: 'Desperdício e cortesias registrados com motivo.' },
        { title: 'Botões rápidos', text: 'Seus produtos mais vendidos a um toque.' },
        { title: 'Várias filiais', text: 'Produção central e transferências para cada unidade.' },
      ],
      faq: [
        { q: 'Serve se eu não tenho mesas, só balcão?', a: 'Sim. Você pode vender no modo balcão, por mesas ou combinar os dois no mesmo negócio.' },
        { q: 'Posso ter comandas em tela na cozinha?', a: 'Sim, ou em impressoras por estação: cozinha, bar ou sobremesas.' },
        { q: 'Recebo pedidos de apps de delivery?', a: 'Há conectores com apps de delivery; veja em Integrações quais estão disponíveis.' },
        { q: 'Posso produzir em uma filial e vender em outras?', a: 'Sim, com ordens de produção e transferências entre depósitos.' },
      ],
    },
    hospedaje: {
      name: 'Hotéis, hospedagem e turismo',
      short: 'Tudo o que se reserva por noite ou por dia: quartos, chalés e espaços.',
      types: [
        'Hotéis',
        'Hostels',
        'Chalés',
        'Glamping',
        'Sítios e casas de temporada',
        'Apartamentos para temporada',
        'Motéis',
        'Clubes e resorts',
        'Pousadas e hotéis ecológicos',
        'Agências e pacotes turísticos',
      ],
      headline: 'Sua hospedagem cheia, sem reservas em conflito.',
      lead: 'Calendário de ocupação, check-in e check-out, folios por hóspede, limpeza e manutenção, e sincronização com Booking.com, Expedia e Airbnb. Com motor de reservas próprio no seu site.',
      pains: [
        { pain: 'Overbooking entre os portais e a recepção.', answer: 'Disponibilidade sincronizada em todos os canais.' },
        { pain: 'Você paga comissão em quase todas as suas reservas.', answer: 'Motor de reservas diretas no seu próprio site.' },
        { pain: 'Os consumos do hóspede são esquecidos no check-out.', answer: 'Folios com lançamentos do restaurante, frigobar e serviços.' },
        { pain: 'As reservas chegam pelo WhatsApp e são anotadas em um caderno.', answer: 'Um calendário único, com sinal e confirmação.' },
      ],
      day: [
        { moment: 'De manhã', title: 'Você confere chegadas e saídas', text: 'A equipe de limpeza sabe qual quarto, chalé ou espaço preparar.' },
        { moment: 'Meio-dia', title: 'Check-out', text: 'Folio fechado e nota fiscal enviada ao hóspede.' },
        { moment: 'À tarde', title: 'Check-in', text: 'Registro de hóspedes e atribuição da acomodação.' },
        { moment: 'À noite', title: 'Novas reservas', text: 'Chegam dos portais e do seu site ao mesmo calendário.' },
      ],
      channel: { title: 'Motor de reservas direto', text: 'Seu site com fotos, tarifas e disponibilidade real para reservar e pagar o sinal sem intermediários.' },
      features: [
        { title: 'Calendário de ocupação', text: 'Por tipo de quarto, chalé ou espaço, com bloqueios.' },
        { title: 'Sincronização com portais', text: 'Booking.com, Expedia, Airbnb e iCal.' },
        { title: 'Tarifas flexíveis', text: 'Por temporada, noite, dia ou número de pessoas.' },
        { title: 'Limpeza e manutenção', text: 'Tarefas priorizadas por chegada e saída.' },
        { title: 'Folios e consumos', text: 'Restaurante, frigobar e serviços lançados na conta.' },
        { title: 'Grupos e empresas', text: 'Reservas de grupo, pacotes e contas corporativas.' },
        { title: 'Sinal on-line', text: 'Pagamentos pelos meios de pagamento integrados.' },
        { title: 'Hóspedes frequentes', text: 'Histórico, preferências e comunicação.' },
      ],
      faq: [
        { q: 'Funciona para chalés, glamping ou sítios?', a: 'Sim. Você configura seus espaços, tipos, capacidade e tarifas de acordo com a sua operação, sejam quartos ou unidades independentes.' },
        { q: 'E se eu também tiver restaurante ou área de piscina e spa?', a: 'Os consumos são vendidos no PDV e lançados no folio do hóspede.' },
        { q: 'Posso cobrar sinal?', a: 'Sim, pelo motor de reservas com pagamentos on-line.' },
      ],
    },
    'espacios-y-eventos': {
      name: 'Espaços, quadras e eventos',
      short: 'Tudo o que se reserva por hora: quadras, salões, clubes e atividades.',
      types: [
        'Quadras society',
        'Clubes sociais e esportivos',
        'Salões de festas e eventos',
        'Coworkings e salas de reunião',
        'Parques de lazer',
        'Piscinas e centros de lazer',
        'Escape rooms',
        'Estúdios de gravação e fotografia',
        'Passeios e experiências',
      ],
      headline: 'Seus espaços reservados, sem conflitos.',
      lead: 'Reservas por hora ou por período, sinal on-line, ingressos e consumos no mesmo lugar. Seus clientes veem a disponibilidade real no seu site e reservam sozinhos.',
      pains: [
        { pain: 'Dois grupos chegam à mesma quadra no mesmo horário.', answer: 'Um calendário por espaço com disponibilidade real.' },
        { pain: 'Reservas que não aparecem e o espaço fica vazio.', answer: 'Sinal on-line e confirmação automática.' },
        { pain: 'Lanchonete, aluguel e ingressos são cobrados separadamente.', answer: 'Tudo no mesmo caixa e no mesmo relatório.' },
      ],
      day: [
        { moment: 'De manhã', title: 'Você confere a agenda', text: 'Espaços reservados, sinais recebidos e o que falta cobrar.' },
        { moment: 'O dia todo', title: 'Reservas pelo seu site', text: 'Seus clientes escolhem espaço, data e horário e pagam o sinal.' },
        { moment: 'Durante o uso', title: 'Consumos e ingressos', text: 'Bebidas, aluguel de equipamentos e ingressos no PDV.' },
        { moment: 'No fechamento', title: 'Fechamento', text: 'Ocupação por espaço, vendas e notas fiscais.' },
      ],
      channel: { title: 'Reserva de espaços on-line', text: 'Seus clientes reservam quadra, salão ou atividade por hora pelo seu site e pagam o sinal.' },
      features: [
        { title: 'Reservas por hora', text: 'Blocos de tempo por espaço, com duração mínima.' },
        { title: 'Tarifas por horário', text: 'Preços diferentes no horário de pico, fins de semana ou feriados.' },
        { title: 'Sinal e depósitos', text: 'Pagamentos on-line na hora de reservar.' },
        { title: 'Consumos no local', text: 'Lanchonete, aluguel de equipamentos e ingressos.' },
      ],
      faq: [
        { q: 'Posso ter várias quadras ou salões?', a: 'Sim. Cada espaço tem seu calendário, capacidade e tarifa.' },
        { q: 'Serve para clubes com sócios?', a: 'Sim. Os sócios são cadastrados como clientes e você pode combinar reservas com planos pela solução Academias, cursos e planos.' },
      ],
    },
    comercio: {
      name: 'Lojas e comércio',
      short: 'Tudo o que vende produtos: na loja física, on-line ou no atacado.',
      types: [
        'Mercadinhos e supermercados',
        'Roupas, calçados e acessórios',
        'Lojas de materiais de construção',
        'Farmácias e drogarias',
        'Eletrônicos e celulares',
        'Papelarias e livrarias',
        'Pet shops',
        'Cosméticos e beleza',
        'Móveis e decoração',
        'Distribuidoras e atacadistas',
        'Lojas só on-line',
      ],
      headline: 'Venda na loja e on-line com um só estoque.',
      lead: 'PDV com código de barras, variações, tabelas de preço, estoque por filial, loja virtual conectada e faturamento na própria venda.',
      pains: [
        { pain: 'Você vende on-line algo que já não está na loja.', answer: 'Um só estoque para a loja física e a virtual.' },
        { pain: 'Controlar tamanhos, cores ou apresentações é um caos.', answer: 'Variações com estoque e código de barras próprios.' },
        { pain: 'Você não sabe quais produtos giram e quais ficam parados.', answer: 'Relatórios de giro e margem por produto.' },
        { pain: 'Seus clientes de atacado pagam preços diferentes.', answer: 'Tabelas de preço e crédito por cliente.' },
      ],
      day: [
        { moment: 'Na abertura', title: 'Você confere o estoque', text: 'Saldos por filial e alertas de reposição.' },
        { moment: 'Durante o dia', title: 'Você vende no balcão', text: 'Código de barras, pagamentos combinados e nota fiscal.' },
        { moment: 'À tarde', title: 'Chegam os pedidos on-line', text: 'Você separa, despacha e fatura.' },
        { moment: 'No fechamento', title: 'Fechamento e compras', text: 'Vendas por vendedor e canal, e pedidos a fornecedores.' },
      ],
      channel: { title: 'Sua loja virtual, pronta', text: 'Seu catálogo publicado com carrinho, pagamentos, entregas e cupons, conectado ao mesmo estoque.' },
      features: [
        { title: 'Variações', text: 'Tamanhos, cores, apresentações e referências.' },
        { title: 'Código de barras', text: 'Na venda, na compra e nas contagens.' },
        { title: 'Tabelas de preço', text: 'Varejo, atacado ou por cliente.' },
        { title: 'Várias filiais', text: 'Estoque e preços por filial.' },
        { title: 'Compras e fornecedores', text: 'Pedidos de compra e recebimento de mercadoria.' },
        { title: 'Lotes e validades', text: 'Para alimentos, medicamentos e cosméticos.' },
        { title: 'Promoções', text: 'Descontos, cupons e datas sazonais.' },
        { title: 'Garantias', text: 'Números de série e reclamações.' },
      ],
      faq: [
        { q: 'Posso usar leitor de código de barras?', a: 'Sim, no PDV, nas compras e nas contagens.' },
        { q: 'Serve para vendas no atacado?', a: 'Sim: tabelas de preço, orçamentos, crédito e contas a receber por cliente.' },
        { q: 'Posso vender só on-line, sem loja física?', a: 'Sim. A loja virtual funciona sozinha, com o mesmo estoque e faturamento.' },
      ],
    },
    'belleza-y-salud': {
      name: 'Beleza, saúde e bem-estar',
      short: 'Tudo o que trabalha com agendamentos: serviços, profissionais e agenda.',
      types: [
        'Salões de beleza e barbearias',
        'Spas e clínicas de estética',
        'Unhas e cílios',
        'Consultórios',
        'Odontologia',
        'Fisioterapia',
        'Psicologia e terapias',
        'Clínicas veterinárias',
        'Óticas',
        'Estúdios de tatuagem',
      ],
      headline: 'Sua agenda cheia, seus clientes de volta.',
      lead: 'Agendamentos por profissional, lembretes, histórico de cada cliente, venda de serviços e produtos no mesmo caixa e um site onde seus clientes agendam sozinhos.',
      pains: [
        { pain: 'Os horários são marcados pelo WhatsApp e se sobrepõem.', answer: 'Agenda por profissional e por serviço, sem conflitos.' },
        { pain: 'Clientes que faltam ao horário marcado.', answer: 'Lembretes automáticos e sinal opcional.' },
        { pain: 'Você não sabe quanto cada profissional vende.', answer: 'Vendas e serviços por profissional nos seus relatórios.' },
      ],
      day: [
        { moment: 'Na abertura', title: 'Você confere a agenda', text: 'Horários do dia por profissional e por sala.' },
        { moment: 'Durante o dia', title: 'Você atende e recebe', text: 'Serviços e produtos na mesma conta, com nota fiscal.' },
        { moment: 'O dia todo', title: 'Novos agendamentos on-line', text: 'Seus clientes escolhem serviço, profissional e horário.' },
        { moment: 'No fechamento', title: 'Acompanhamento', text: 'Vendas por profissional e clientes para contatar de novo.' },
      ],
      channel: { title: 'Agenda de horários no seu site', text: 'Seus clientes escolhem o serviço, o profissional e o horário, e recebem a confirmação.' },
      features: [
        { title: 'Agenda por profissional', text: 'Horários, serviços e salas de cada pessoa.' },
        { title: 'Lembretes', text: 'Por e-mail ou WhatsApp antes de cada horário.' },
        { title: 'Histórico do cliente', text: 'Serviços, compras e anotações de cada visita.' },
        { title: 'Serviços e produtos', text: 'Na mesma conta, com estoque de insumos.' },
      ],
      faq: [
        { q: 'Meus clientes podem agendar sozinhos?', a: 'Sim, pelo seu site, escolhendo serviço, profissional e horário disponível.' },
        { q: 'Posso vender pacotes de sessões?', a: 'Sim, como produtos ou planos que o cliente usa em várias visitas.' },
      ],
    },
    'gimnasios-y-academias': {
      name: 'Academias, cursos e planos',
      short: 'Tudo o que cobra planos: alunos, aulas, acessos e renovações.',
      types: [
        'Academias',
        'Treinamento funcional',
        'Yoga, pilates e dança',
        'Escolas de idiomas e cursos',
        'Escolinhas esportivas',
        'Clubes com sócios',
        'Artes marciais',
        'Escolas de natação',
      ],
      headline: 'Planos em dia, aulas cheias.',
      lead: 'Planos e mensalidades, trancamentos, controle de acesso com QR, aulas com vagas e reservas, e cobranças recorrentes. Com site próprio para vender planos e reservar aulas.',
      pains: [
        { pain: 'Alunos entrando com o plano vencido.', answer: 'Acesso validado de acordo com a situação do plano.' },
        { pain: 'As aulas lotam demais ou ficam vazias.', answer: 'Vagas e reservas pelo celular.' },
        { pain: 'Cobrar as mensalidades é correr atrás das pessoas.', answer: 'Lembretes e pagamentos on-line.' },
      ],
      day: [
        { moment: 'Na abertura', title: 'Entradas', text: 'Check-in com QR e alertas de vencimento.' },
        { moment: 'Durante o dia', title: 'Aulas', text: 'Presença de quem reservou.' },
        { moment: 'Meio-dia', title: 'Vendas', text: 'Planos, produtos e renovações.' },
        { moment: 'No fechamento', title: 'Acompanhamento', text: 'Alunos com plano a vencer e inativos.' },
      ],
      channel: { title: 'Reserva de aulas e venda de planos', text: 'Seus alunos reservam aulas e renovam o plano pelo seu site.' },
      features: [
        { title: 'Planos e mensalidades', text: 'Mensais, trimestrais, anuais ou por sessões.' },
        { title: 'Trancamentos', text: 'Pausas com data de reativação.' },
        { title: 'Acesso com QR', text: 'Check-in e catracas de acesso.' },
        { title: 'Aulas e vagas', text: 'Horários, instrutores e reservas.' },
      ],
      faq: [
        { q: 'Serve para escolas ou cursos, não só academias?', a: 'Sim. Os cursos são gerenciados como planos com horários, vagas e presença.' },
        { q: 'Posso cobrar por sessões avulsas?', a: 'Sim. Você pode vender planos por número de sessões ou entradas avulsas.' },
      ],
    },
    movilidad: {
      name: 'Estacionamentos, transporte e mobilidade',
      short: 'Tudo o que movimenta ou guarda veículos: vagas, rotas, passagens e envios.',
      types: [
        'Estacionamentos',
        'Lava-rápidos',
        'Transporte de passageiros',
        'Fretamento e transporte turístico',
        'Encomendas e entregas',
        'Locadoras de veículos',
        'Oficinas e centros automotivos',
      ],
      headline: 'Cada veículo, cada minuto, cobrado.',
      lead: 'Entradas e saídas por placa com tarifa por tempo, mensalistas, rotas e passagens com assento, envios com etiqueta, frota e motoristas, sincronizados com o caixa e o faturamento.',
      pains: [
        { pain: 'Tíquetes de papel que se perdem.', answer: 'Entrada registrada pela placa com tíquete impresso ou digital.' },
        { pain: 'Cobranças mal calculadas na saída.', answer: 'Tarifas por minuto, hora ou dia aplicadas automaticamente.' },
        { pain: 'Assentos vendidos em dobro na mesma viagem.', answer: 'Atribuição de assento por viagem.' },
        { pain: 'Documentos da frota vencendo.', answer: 'Veículos e habilitações com alertas.' },
      ],
      day: [
        { moment: 'Na abertura', title: 'Você abre o turno', text: 'Caixa, ocupação inicial e saídas do dia.' },
        { moment: 'Horário de pico', title: 'Entradas e vendas', text: 'Registro por placa e passagens no guichê e on-line.' },
        { moment: 'À tarde', title: 'Envios e saídas', text: 'Etiquetas, entregas e cobranças calculadas.' },
        { moment: 'No fechamento', title: 'Fechamento de turno', text: 'Conferência de caixa, ocupação e arrecadação por rota ou por operador.' },
      ],
      channel: { title: 'Tarifas, mensalidades e passagens on-line', text: 'Publique tarifas, horários e localização; venda mensalidades ou passagens com assento pelo seu site.' },
      features: [
        { title: 'Mapa de vagas', text: 'Áreas e tipos de veículo.' },
        { title: 'Tarifas por tempo', text: 'Por minuto, hora, dia ou fração.' },
        { title: 'Mensalistas', text: 'Planos com veículos autorizados.' },
        { title: 'Rotas e passagens', text: 'Horários, paradas e mapa de assentos.' },
        { title: 'Envios', text: 'Etiquetas, manifestos e comprovante de entrega.' },
        { title: 'Frota', text: 'Veículos, motoristas e ocorrências.' },
        { title: 'Turnos', text: 'Fechamento por operador.' },
        { title: 'Serviços ao veículo', text: 'Lavagem, estacionamento e serviços na mesma conta.' },
      ],
      faq: [
        { q: 'Posso ter várias tarifas conforme o veículo?', a: 'Sim, por tipo de veículo e horário.' },
        { q: 'Vocês trabalham com encomendas?', a: 'Sim: etiquetas, manifestos, tentativas de entrega e comprovante de entrega.' },
      ],
    },
    servicios: {
      name: 'Serviços e empresas',
      short: 'Tudo o que vende conhecimento ou trabalho: projetos, orçamentos e cobranças.',
      types: [
        'Agências e consultorias',
        'Escritórios de contabilidade e advocacia',
        'Construção e manutenção',
        'Oficinas e assistência técnica',
        'Educação e escolas',
        'Empresas de software',
        'Imobiliárias',
        'Segurança e limpeza',
        'Fundações e ONGs',
      ],
      headline: 'Do primeiro contato à última cobrança.',
      lead: 'Oportunidades, orçamentos, agenda, projetos com tarefas e horas, faturamento, contabilidade e contas a receber, no mesmo lugar.',
      pains: [
        { pain: 'Você faz orçamentos no Word e perde o acompanhamento.', answer: 'Orçamentos ligados ao funil de vendas.' },
        { pain: 'Você não sabe se um projeto dá lucro.', answer: 'Horas e custos por projeto.' },
        { pain: 'As contas a receber se acumulam.', answer: 'Parcelas e lembretes de cobrança.' },
      ],
      day: [
        { moment: 'De manhã', title: 'Agenda do dia', text: 'Compromissos, tarefas e reuniões.' },
        { moment: 'Meio-dia', title: 'Você faz orçamentos', text: 'A partir da oportunidade, com acompanhamento.' },
        { moment: 'À tarde', title: 'Você executa', text: 'Projetos, marcos e horas registradas.' },
        { moment: 'No fechamento', title: 'Você cobra', text: 'Nota fiscal e lembrete automático.' },
      ],
      channel: { title: 'Site com agenda e formulário', text: 'Apresente seus serviços, receba solicitações e deixe seus clientes agendarem.' },
      features: [
        { title: 'Orçamentos', text: 'Com modelos e aprovação.' },
        { title: 'Projetos', text: 'Marcos, tarefas e equipe.' },
        { title: 'Horas', text: 'Registro de tempo por tarefa.' },
        { title: 'Contas a receber', text: 'Parcelas e lembretes.' },
      ],
      faq: [
        { q: 'Serve para empresas com cobranças recorrentes?', a: 'Sim: planos, assinaturas e faturamento periódico.' },
        { q: 'Meu contador pode acessar?', a: 'Sim, com um perfil que só vê contabilidade e relatórios.' },
      ],
    },
  },

  integrations: {
    groups: {
      pagos: {
        name: 'Pagamentos e bancos',
        text: 'Receba on-line, por QR ou na maquininha e concilie suas contas.',
        items: {
          'Wompi': 'Pagamentos on-line.',
          'PSE': 'Débito direto em conta bancária.',
          'Nequi': 'Pagamentos pela carteira digital.',
          'DaviPlata': 'Pagamentos pela carteira digital.',
          'SPEI': 'Transferências instantâneas.',
          'OXXO Pay': 'Pagamentos em dinheiro na loja.',
          'Conekta': 'Cartões e pagamentos on-line.',
          'PayU': 'Cartões e meios de pagamento locais.',
          'Mercado Pago': 'Pagamentos on-line e QR.',
          'Bold': 'Maquininhas e links de pagamento.',
          'Bre-B': 'Pagamentos instantâneos do Banco de la República.',
          'Bancolombia': 'Contas e extratos.',
          'Redeban': 'Maquininhas e adquirência.',
          'Stripe': 'Pagamentos internacionais.',
          'PayPal': 'Pagamentos internacionais.',
          'Venmo': 'Pagamentos entre pessoas.',
          'Cash App': 'Pagamentos entre pessoas.',
          'Zelle': 'Transferências bancárias.',
        },
      },
      reservas: {
        name: 'Canais de reserva',
        text: 'Disponibilidade e reservas sincronizadas com o seu calendário.',
        items: {
          'Booking.com': 'Reservas, tarifas e disponibilidade.',
          'Expedia Group': 'Reservas e disponibilidade.',
          'Airbnb': 'Calendário e reservas.',
          'Google Vacation Rentals': 'Presença no Google.',
          'TripAdvisor': 'Presença e avaliações.',
        },
      },
      domicilios: {
        name: 'Delivery e envios',
        text: 'Pedidos de apps e etiquetas de transportadoras.',
        items: {
          'Rappi': 'Pedidos de delivery.',
          'Uber Eats': 'Pedidos de delivery.',
          'iFood': 'Pedidos de delivery.',
          'Coordinadora': 'Etiquetas e rastreamento.',
          'Servientrega': 'Etiquetas e rastreamento.',
          'Interrapidísimo': 'Etiquetas e rastreamento.',
          'Envía': 'Cotação de frete e etiquetas.',
        },
      },
      mensajeria: {
        name: 'Mensagens',
        text: 'Converse com seus clientes e envie notificações.',
        items: {
          'WhatsApp Business': 'Chat, campanhas e notificações.',
          'Twilio': 'SMS e ligações.',
          'SendGrid': 'E-mails transacionais.',
        },
      },
      marketing: {
        name: 'Redes e publicidade',
        text: 'Catálogo, mensagens e campanhas.',
        items: {
          'Meta (Facebook, Instagram)': 'Mensagens e catálogo.',
          'TikTok Business': 'Catálogo e campanhas.',
          'Google Ads': 'Conversões e campanhas.',
        },
      },
    },
    developer: [
      { title: 'API', text: 'Consulte e crie informações da sua organização com chaves de acesso.' },
      { title: 'Webhooks', text: 'Receba eventos quando algo acontece: uma venda, uma reserva, um pagamento.' },
      { title: 'Sincronizações', text: 'Tarefas agendadas com registro de cada execução.' },
    ],
  },
}
