/**
 * Catalogue en français (produits, solutions et intégrations).
 * Même forme et même ordre que le texte de base en espagnol (lib/catalog).
 */
import type { CatalogText } from '../types'

export const catalog: CatalogText = {
  categories: {
    operacion: { name: 'Opérations', text: 'Ce qui se passe à la caisse, à l’entrepôt et dans les chambres.' },
    finanzas: { name: 'Finances et équipe', text: 'Factures, comptes et paie à jour.' },
    clientes: { name: 'Clients', text: 'Chaque conversation et chaque vente, dans un seul historique.' },
    canales: { name: 'Canaux numériques', text: 'Votre entreprise en ligne dès le premier jour.' },
    inteligencia: { name: 'Données et IA', text: 'Des réponses claires pour décider.' },
  },

  products: {
    // -----------------------------------------------------------------------
    // Opérations
    // -----------------------------------------------------------------------
    'ventas-pos': {
      name: 'Ventes et point de vente',
      short: 'Caisse, tables, commandes et paiements.',
      eyebrow: 'Ventes et PDV',
      headline: 'Encaissez sans files ni cahiers.',
      lead: 'Un point de vente pour commerce, restaurant ou centre d’entraînement. Chaque vente met à jour l’inventaire, est prête à facturer et apparaît dans vos rapports.',
      pains: [
        { pain: 'À la fermeture, la caisse ne balance pas et vous ne savez pas pourquoi.', answer: 'Comptage par mode de paiement et écarts expliqués à la fermeture.' },
        { pain: 'Les commandes des tables se perdent entre le bar et la cuisine.', answer: 'Des bons qui arrivent en cuisine par poste, avec leur statut en temps réel.' },
        { pain: 'Vous vendez un article qui n’est plus en stock.', answer: 'Le stock baisse à chaque vente et vous avertit avant la rupture.' },
      ],
      features: [
        { title: 'Ouverture et fermeture de caisse', text: 'Fonds de caisse, mouvements, comptage et décompte par coupure.' },
        { title: 'Tables et commandes', text: 'Plan de salle par zone, additions séparées, pourboires et frais de service.' },
        { title: 'Tous les modes de paiement', text: 'Comptant, carte, virement et paiement par code QR dans une même vente.' },
        { title: 'Promotions et coupons', text: 'Règles de rabais, coupons et prix par liste ou par succursale.' },
        { title: 'Retours bien gérés', text: 'Motifs de retour, note de crédit et remise en inventaire.' },
        { title: 'Imprimantes et terminaux', text: 'Reçus, bons par poste et plusieurs caisses par site.' },
      ],
      steps: [
        { title: 'Ouvrez la caisse', text: 'Saisissez le fonds de caisse et qui est en service.' },
        { title: 'Vendez', text: 'Cherchez par nom ou code-barres, encaissez avec un ou plusieurs modes de paiement.' },
        { title: 'Facturez', text: 'Émettez la facture ou le reçu depuis la même vente.' },
        { title: 'Fermez', text: 'Le comptage compare l’argent compté aux ventes.' },
      ],
      highlights: ['Ventes par site et par caissier', 'Bons vers la cuisine et le bar', 'Facturation dans le même flux'],
      faq: [
        { q: 'Est-ce que ça fonctionne sur tablette ou cellulaire ?', a: 'Oui. GO Admin fonctionne dans le navigateur de l’ordinateur, de la tablette ou du cellulaire.' },
        { q: 'Puis-je avoir plusieurs caisses sur le même site ?', a: 'Oui. Chaque caisse a son ouverture, ses mouvements et sa fermeture.' },
        { q: 'Est-ce compatible avec les imprimantes de reçus et de bons ?', a: 'Oui. Vous assignez des imprimantes par poste pour que chaque zone reçoive ce qui la concerne.' },
      ],
    },
    inventario: {
      name: 'Inventaire',
      short: 'Stock par entrepôt, lots et transferts.',
      eyebrow: 'Inventaire',
      headline: 'Sachez ce que vous avez, et où.',
      lead: 'Stocks par entrepôt et par succursale, coûts, lots et transferts. Chaque vente retire, chaque achat ajoute, sans tableur.',
      pains: [
        { pain: 'Vous comptez l’inventaire et il ne correspond jamais au système.', answer: 'Comptages cycliques, ajustements motivés et fiche de chaque mouvement (kardex).' },
        { pain: 'Vous ne savez pas combien vous coûte vraiment ce que vous vendez.', answer: 'Coût moyen et PEPS mis à jour à chaque achat.' },
        { pain: 'Vous déplacez de la marchandise entre sites et vous en perdez la trace.', answer: 'Transferts avec sortie, transit et réception avec écarts.' },
      ],
      features: [
        { title: 'Catalogue complet', text: 'Catégories en arborescence, variantes (taille, couleur), images, unités et codes-barres.' },
        { title: 'Stock en temps réel', text: 'Stocks par entrepôt et par succursale avec alertes de seuil minimal.' },
        { title: 'Achats et fournisseurs', text: 'Bons de commande, réception et lien avec les comptes fournisseurs.' },
        { title: 'Lots et numéros de série', text: 'Dates d’expiration, garanties et traçabilité par numéro de série.' },
        { title: 'Recettes et production', text: 'Déduit les ingrédients quand vous vendez un plat ou produisez un lot.' },
        { title: 'Kardex et ajustements', text: 'Historique de chaque mouvement : qui, quand et pourquoi.' },
      ],
      steps: [
        { title: 'Importez votre catalogue', text: 'Chargez produits et stocks depuis Excel.' },
        { title: 'Définissez entrepôts et seuils', text: 'Par site et par produit.' },
        { title: 'Opérez', text: 'Ventes, achats et transferts mettent le stock à jour tout seuls.' },
        { title: 'Comptez et ajustez', text: 'Comptages cycliques avec écarts expliqués.' },
      ],
      highlights: ['Multientrepôt et multisite', 'Variantes et codes-barres', 'Coût moyen et PEPS'],
      faq: [
        { q: 'Puis-je gérer des tailles et des couleurs ?', a: 'Oui. Vous créez des types de variantes et chaque combinaison a son propre stock et son propre code.' },
        { q: 'Est-ce adapté aux restaurants ?', a: 'Oui. Avec les recettes, chaque plat vendu déduit ses ingrédients.' },
        { q: 'Comment charger mon inventaire initial ?', a: 'Vous importez depuis Excel et nous vous accompagnons lors du premier chargement.' },
      ],
    },
    hoteleria: {
      name: 'Hôtellerie (PMS)',
      short: 'Réservations, arrivées, folios et canaux.',
      eyebrow: 'Hôtellerie',
      headline: 'Réservations et chambres sans chevauchements.',
      lead: 'Calendrier d’occupation, arrivées et départs, folios par client, tarifs et connexion avec des canaux comme Booking.com et Expedia.',
      pains: [
        { pain: 'Une chambre vendue deux fois sur des canaux différents.', answer: 'Disponibilité synchronisée avec les canaux de réservation.' },
        { pain: 'Les consommations des clients restent sur papier.', answer: 'Folios avec les frais du restaurant, du minibar et des services.' },
        { pain: 'L’entretien ménager ne sait pas quelles chambres nettoyer en premier.', answer: 'Tâches de ménage et d’entretien selon les départs et les arrivées.' },
      ],
      features: [
        { title: 'Calendrier des réservations', text: 'Vue par type de chambre, blocages et groupes.' },
        { title: 'Arrivée et départ', text: 'Enregistrement des clients et départ avec folio fermé.' },
        { title: 'Folios multicomptes', text: 'Frais séparés par client ou par entreprise.' },
        { title: 'Tarifs et extras', text: 'Tarifs saisonniers, forfaits et services additionnels.' },
        { title: 'Gestionnaire de canaux', text: 'Booking.com, Expedia, Airbnb et calendriers iCal.' },
        { title: 'Entretien ménager', text: 'Tâches de ménage et bons de travail d’entretien.' },
      ],
      steps: [
        { title: 'Configurez les chambres', text: 'Types, espaces, tarifs et services.' },
        { title: 'Connectez les canaux', text: 'Associez vos types de chambres à chaque canal.' },
        { title: 'Recevez des réservations', text: 'Depuis les canaux, votre moteur de réservation ou la réception.' },
        { title: 'Facturez le séjour', text: 'Le folio devient une facture au départ.' },
      ],
      highlights: ['Moteur de réservation intégré', 'Booking.com et Expedia', 'Folios et facturation'],
      faq: [
        { q: 'Est-ce que ça se connecte à Booking.com ?', a: 'Oui. Vous associez vos types de chambres et vos tarifs, et les réservations arrivent dans le calendrier.' },
        { q: 'Puis-je porter les consommations du restaurant à la chambre ?', a: 'Oui. Les frais du point de vente peuvent aller au folio du client.' },
      ],
    },

    // -----------------------------------------------------------------------
    // Finances et équipe
    // -----------------------------------------------------------------------
    'facturacion-electronica': {
      name: '{invoicing}',
      short: 'Factures validées par {theAuthority}, depuis la vente.',
      eyebrow: '{invoicing}',
      headline: 'Facturez là où vous vendez.',
      lead: 'Émettez factures, notes de crédit et documents justificatifs validés par {theAuthority} depuis le point de vente ou les finances, et suivez leur statut au même endroit.',
      pains: [
        { pain: 'Vous facturez dans un autre logiciel et saisissez tout deux fois.', answer: 'La facture part de la vente, avec le client, les produits et les taxes.' },
        { pain: 'Vous ne savez pas si {theAuthority} a accepté ou rejeté un document.', answer: 'Le statut de chaque document, avec l’erreur expliquée s’il y en a une.' },
        { pain: 'Les notes de crédit et les retours s’emmêlent.', answer: 'Note de crédit liée à la facture et au retour.' },
      ],
      features: [
        { title: 'Facture de vente', text: 'Numérotation, résolutions de facturation et envoi au client par courriel.' },
        { title: 'Notes de crédit et de débit', text: 'Liées à la facture d’origine et aux retours.' },
        { title: 'Document justificatif', text: 'Pour les achats auprès de fournisseurs non tenus de facturer.' },
        { title: 'Taxes et retenues', text: '{taxes} configurables par produit et par client.' },
        { title: 'Validation par {theAuthority}', text: '{docId}, code QR et réponse de validation de chaque document.' },
        { title: 'Consultation des clients', text: 'Données fiscales du client pour éviter les erreurs.' },
      ],
      steps: [
        { title: 'Activez le service', text: 'Configurez votre résolution de facturation et votre certificat de signature.' },
        { title: 'Vendez', text: 'Depuis le PDV, une soumission ou les finances.' },
        { title: 'Émettez', text: 'Le document est validé et envoyé au client.' },
        { title: 'Consultez', text: 'Statut, PDF et XML toujours à portée de main.' },
      ],
      highlights: ['Incluse dans tous les forfaits', 'Factures, notes et documents justificatifs', 'Validation par {theAuthority} en temps réel'],
      faq: [
        { q: 'Ai-je besoin d’un certificat numérique ?', a: 'Oui, pour signer les documents. Si vous n’en avez pas, vous pouvez l’acquérir en option.' },
        { q: 'Combien de factures puis-je émettre ?', a: 'Cela dépend du forfait : 1 000, 3 000 ou illimitées par mois. Vous pouvez ajouter des factures supplémentaires.' },
        { q: 'Puis-je facturer depuis mon cellulaire ?', a: 'Oui. La facturation fonctionne dans le navigateur, sur n’importe quel appareil.' },
      ],
      variants: {
        noEInvoice: {
          short: 'Factures avec les taxes de votre pays.',
          lead: 'Émettez factures et notes de crédit avec {taxes}, depuis le point de vente ou les finances, et envoyez-les à votre client. {einvoiceNote}',
          pains: [
            { pain: 'Vous facturez dans un autre logiciel et saisissez tout deux fois.', answer: 'La facture part de la vente, avec le client, les produits et les taxes.' },
            { pain: 'Vous calculez les taxes à la main sur chaque facture.', answer: '{taxes} configurées par produit et par client.' },
            { pain: 'Les notes de crédit et les retours s’emmêlent.', answer: 'Note de crédit liée à la facture et au retour.' },
          ],
          features: [
            { title: 'Facture de vente', text: 'Numérotation, PDF et envoi au client par courriel.' },
            { title: 'Notes de crédit et de débit', text: 'Liées à la facture d’origine et aux retours.' },
            { title: 'Plusieurs devises', text: 'Factures dans votre devise et dans d’autres, avec taux de change.' },
            { title: 'Taxes de votre pays', text: '{taxes} configurables par produit et par client.' },
            { title: 'Données fiscales', text: 'Identification de vos clients avec {taxId} et les documents de votre pays.' },
            { title: 'Consultation des clients', text: 'Historique des factures, paiements et soldes par client.' },
          ],
          steps: [
            { title: 'Configurez', text: 'Numérotation, taxes et données de votre entreprise.' },
            { title: 'Vendez', text: 'Depuis le PDV, une soumission ou les finances.' },
            { title: 'Émettez', text: 'Le document est généré et envoyé au client.' },
            { title: 'Consultez', text: 'Statut, PDF et paiements toujours à portée de main.' },
          ],
          highlights: ['Taxes de votre pays configurées', 'Factures et notes de crédit', 'Liée aux ventes et à la comptabilité'],
          faq: [
            { q: 'Comment fonctionne la facturation électronique {inCountry} ?', a: '{einvoiceNote}' },
            { q: 'Combien de factures puis-je émettre ?', a: 'Cela dépend du forfait : 1 000, 3 000 ou illimitées par mois.' },
            { q: 'Puis-je facturer depuis mon cellulaire ?', a: 'Oui. La facturation fonctionne dans le navigateur, sur n’importe quel appareil.' },
          ],
        },
      },
    },
    contabilidad: {
      name: 'Comptabilité et finances',
      short: 'Écritures, comptes clients, banques et clôtures.',
      eyebrow: 'Comptabilité',
      headline: 'Des comptes clairs, sans ressaisie.',
      lead: 'Chaque vente, achat et paiement génère son écriture. Comptes clients, comptes fournisseurs, banques, rapprochement et clôtures dans le système où vous travaillez déjà.',
      pains: [
        { pain: 'Votre comptable reçoit l’information en retard et en fichiers épars.', answer: 'Écritures automatiques issues des opérations, prêtes à réviser.' },
        { pain: 'Vous ne savez pas qui vous doit ni à qui vous devez.', answer: 'Comptes clients et fournisseurs avec échéances et rappels.' },
        { pain: 'Le rapprochement bancaire prend des jours.', answer: 'Rapprochement avec les mouvements importés de la banque.' },
      ],
      features: [
        { title: 'Plan comptable', text: 'Basé sur le {chart}, avec des règles comptables configurables.' },
        { title: 'Écritures automatiques', text: 'Ventes, achats, paiements et paie se comptabilisent tout seuls.' },
        { title: 'Comptes clients et fournisseurs', text: 'Versements, échéances et rappels de paiement.' },
        { title: 'Banques et rapprochement', text: 'Comptes bancaires, virements et rapprochement.' },
        { title: 'Centres de coûts et budgets', text: 'Résultats par site, service ou projet.' },
        { title: 'Immobilisations et clôtures', text: 'Amortissements et exercices financiers.' },
      ],
      steps: [
        { title: 'Configurez', text: 'Plan comptable, taxes et règles comptables.' },
        { title: 'Opérez', text: 'Chaque document génère son écriture.' },
        { title: 'Rapprochez', text: 'Croisez banques, comptes clients et paiements.' },
        { title: 'Clôturez le mois', text: 'Révisez, ajustez et verrouillez la période.' },
      ],
      highlights: ['Plan comptable et règles comptables', 'Rapprochement bancaire', 'Centres de coûts et budgets'],
      faq: [
        { q: 'Mon comptable peut-il travailler dans GO Admin ?', a: 'Oui. Vous lui donnez un utilisateur avec le rôle et les permissions dont il a besoin.' },
        { q: 'Que se passe-t-il si une écriture échoue ?', a: 'Elle reste enregistrée pour être révisée et corrigée, sans perdre le document d’origine.' },
      ],
    },
    nomina: {
      name: 'Paie et équipe',
      short: 'Contrats, quarts de travail et paie électronique.',
      eyebrow: 'Paie et équipe',
      headline: 'Votre équipe, bien organisée.',
      lead: 'Employés, contrats, quarts, présences, vacances, prêts et paie au même endroit, en lien avec la comptabilité.',
      pains: [
        { pain: 'Les horaires vivent dans un groupe WhatsApp.', answer: 'Modèles de quarts et rotations visibles par tous.' },
        { pain: 'Calculer la paie prend une journée entière.', answer: 'Périodes, événements de paie et talons de paie calculés.' },
        { pain: 'Vous ne savez pas combien de jours de vacances il reste à chacun.', answer: 'Soldes de vacances et de congés à jour.' },
      ],
      features: [
        { title: 'Employés et contrats', text: 'Postes, services, salaires et documents.' },
        { title: 'Quarts et rotations', text: 'Modèles et affectations par site.' },
        { title: 'Présences', text: 'Pointages d’entrée et de sortie et feuilles de temps.' },
        { title: 'Vacances et congés', text: 'Demandes, approbations et soldes.' },
        { title: 'Paie', text: 'Périodes, événements de paie, talons de paie et paie électronique validée par {theAuthority}.' },
        { title: 'Prêts et avances', text: 'Versements retenus à chaque période.' },
      ],
      steps: [
        { title: 'Inscrivez votre équipe', text: 'Données, contrat et salaire.' },
        { title: 'Planifiez les quarts', text: 'Modèles et rotations par site.' },
        { title: 'Saisissez les événements', text: 'Heures supplémentaires, absences et vacances.' },
        { title: 'Calculez la paie', text: 'Talons de paie et écritures comptables.' },
      ],
      highlights: ['Quarts et présences', 'Vacances et congés', 'Paie liée à la comptabilité'],
      faq: [
        { q: 'Les employés peuvent-ils voir leurs quarts ?', a: 'Oui, avec un utilisateur et les permissions que vous définissez pour leur poste.' },
        { q: 'La paie génère-t-elle les écritures comptables ?', a: 'Oui. Chaque paie est comptabilisée.' },
      ],
      variants: {
        noEPayroll: {
          short: 'Contrats, quarts de travail et calcul de la paie.',
          features: [
            { title: 'Employés et contrats', text: 'Postes, services, salaires et documents.' },
            { title: 'Quarts et rotations', text: 'Modèles et affectations par site.' },
            { title: 'Présences', text: 'Pointages d’entrée et de sortie et feuilles de temps.' },
            { title: 'Vacances et congés', text: 'Demandes, approbations et soldes.' },
            { title: 'Paie', text: 'Périodes, événements de paie et talons de paie selon les règles du travail de votre pays.' },
            { title: 'Prêts et avances', text: 'Versements retenus à chaque période.' },
          ],
        },
      },
    },

    // -----------------------------------------------------------------------
    // Clients
    // -----------------------------------------------------------------------
    'clientes-crm': {
      name: 'Clients (CRM)',
      short: 'Historique, occasions d’affaires et campagnes.',
      eyebrow: 'Clients et CRM',
      headline: 'Souvenez-vous de chaque client.',
      lead: 'La fiche de chaque client réunit achats, réservations, conversations et tâches. Occasions dans des entonnoirs de vente, suivis et campagnes par segment.',
      pains: [
        { pain: 'L’information sur le client est dans la tête d’un vendeur.', answer: 'Fiche 360° avec tout l’historique du client.' },
        { pain: 'Les soumissions refroidissent faute de suivi.', answer: 'Entonnoirs avec étapes, tâches et rappels.' },
        { pain: 'Vous envoyez la même promotion à tout le monde.', answer: 'Segments et campagnes selon ce que chaque client achète.' },
      ],
      features: [
        { title: 'Fiche 360°', text: 'Achats, factures, réservations, notes et conversations.' },
        { title: 'Entonnoirs de vente', text: 'Étapes personnalisables, occasions et soumissions.' },
        { title: 'Tâches et activités', text: 'Appels, réunions et rappels par responsable.' },
        { title: 'Segments et campagnes', text: 'Par courriel, WhatsApp ou texto.' },
        { title: 'Automatisations', text: 'Des actions déclenchées par les événements de l’entreprise.' },
        { title: 'Consentements', text: 'Préférences de contact de chaque client.' },
      ],
      steps: [
        { title: 'Rassemblez vos clients', text: 'Importez votre base ou créez-les en vendant.' },
        { title: 'Organisez l’entonnoir', text: 'Définissez les étapes selon votre façon de vendre.' },
        { title: 'Faites le suivi', text: 'Tâches et rappels pour chaque occasion.' },
        { title: 'Communiquez', text: 'Campagnes par segment et automatisations.' },
      ],
      highlights: ['Fiche 360°', 'Entonnoirs et soumissions', 'Campagnes par WhatsApp et courriel'],
      faq: [
        { q: 'Puis-je importer mes clients actuels ?', a: 'Oui, depuis Excel. Ils se créent aussi lors d’une vente ou d’une réservation.' },
        { q: 'Les campagnes partent-elles par WhatsApp ?', a: 'Oui, en connectant votre WhatsApp Business. Aussi par courriel et par texto.' },
      ],
    },
    'chat-omnicanal': {
      name: 'Clavardage omnicanal',
      short: 'WhatsApp, Instagram et Web dans une seule boîte.',
      eyebrow: 'Clavardage omnicanal',
      headline: 'Toutes les conversations dans une seule boîte.',
      lead: 'WhatsApp, Instagram, Facebook et le clavardage de votre site Web arrivent au même endroit. Assignez les conversations à l’équipe et laissez un assistant IA répondre aux questions fréquentes.',
      pains: [
        { pain: 'Vous répondez depuis trois cellulaires différents.', answer: 'Une boîte partagée pour tous les canaux.' },
        { pain: 'Les mêmes questions vous prennent la journée.', answer: 'Réponses rapides et un assistant IA formé avec vos informations.' },
        { pain: 'Vous ne savez pas qui a servi qui.', answer: 'Assignations, statuts et notes internes dans chaque conversation.' },
      ],
      features: [
        { title: 'Boîte unifiée', text: 'WhatsApp, Instagram, Facebook et clavardage Web.' },
        { title: 'Assignation et statuts', text: 'Par agent ou par service, avec historique.' },
        { title: 'Assistant IA', text: 'Répond avec votre catalogue, vos horaires et vos politiques.' },
        { title: 'Réponses rapides', text: 'Des modèles pour les questions qui reviennent toujours.' },
        { title: 'Widget pour votre site', text: 'Clavardage sur votre site Web GO Admin ou sur un autre.' },
        { title: 'Résumés et étiquettes', text: 'Résumés automatiques et étiquettes par sujet.' },
      ],
      steps: [
        { title: 'Connectez vos canaux', text: 'WhatsApp Business, Instagram et votre site.' },
        { title: 'Formez l’assistant', text: 'Avec vos produits, vos prix et vos questions fréquentes.' },
        { title: 'Répondez en équipe', text: 'Assignez, répondez et laissez des notes.' },
        { title: 'Vendez', text: 'La conversation reste dans la fiche du client.' },
      ],
      highlights: ['WhatsApp, Instagram et Web', 'Assistant formé avec vos informations', 'Historique dans le CRM'],
      faq: [
        { q: 'L’assistant répond-il tout seul ?', a: 'Il répond aux questions fréquentes avec l’information que vous lui donnez ; votre équipe peut reprendre la conversation à tout moment.' },
        { q: 'Ai-je besoin de WhatsApp Business ?', a: 'Oui, pour connecter WhatsApp à la boîte partagée.' },
      ],
    },

    // -----------------------------------------------------------------------
    // Canaux numériques
    // -----------------------------------------------------------------------
    'sitio-web': {
      name: 'Site Web',
      short: 'Votre site avec votre propre domaine, prêt en quelques minutes.',
      eyebrow: 'Site Web',
      headline: 'Votre entreprise en ligne dès le premier jour.',
      lead: 'Chaque organisation reçoit son site Web à une adresse GO Admin ou avec son propre domaine. Vous choisissez un modèle, l’adaptez à votre marque, et il se met à jour tout seul avec vos produits, services et horaires.',
      pains: [
        { pain: 'Avoir un site Web voulait dire engager quelqu’un et attendre.', answer: 'Des modèles par secteur, prêts à publier.' },
        { pain: 'Le site devient désuet, avec de vieux prix.', answer: 'Produits, prix et horaires viennent de l’ERP.' },
        { pain: 'Personne ne vous trouve sur Google.', answer: 'Titre, description et image pour les moteurs de recherche et les réseaux sur chaque page.' },
      ],
      features: [
        { title: 'Modèles par secteur', text: 'Moderne, classique, élégant, restaurant, hôtel, boutique et stationnement.' },
        { title: 'Constructeur de pages', text: 'Des sections que vous ordonnez et modifiez, avec brouillon et publication.' },
        { title: 'Domaine personnalisé', text: 'Sous-domaine GO Admin ou votre domaine, avec vérification et certificat.' },
        { title: 'Votre marque', text: 'Logo, couleurs, polices, menus et pied de page.' },
        { title: 'Moteurs de recherche et réseaux', text: 'Métadonnées, image de partage et vérification Google.' },
        { title: 'Visites et avis', text: 'Statistiques de visites et avis de clients modérés.' },
      ],
      steps: [
        { title: 'Choisissez un modèle', text: 'Selon votre secteur.' },
        { title: 'Ajoutez votre marque', text: 'Logo, couleurs et contenu.' },
        { title: 'Connectez votre domaine', text: 'Ou utilisez l’adresse GO Admin.' },
        { title: 'Publiez', text: 'Vos produits et horaires se mettent à jour tout seuls.' },
      ],
      highlights: ['Sous-domaine inclus ou domaine personnalisé', 'Modèles par secteur', 'Contenu relié à l’ERP'],
      faq: [
        { q: 'Puis-je utiliser mon propre domaine ?', a: 'Oui. Vous connectez votre domaine avec une vérification DNS ; vous pouvez aussi l’acheter depuis GO Admin.' },
        { q: 'Dois-je savoir programmer ?', a: 'Non. Vous modifiez sections, textes et images depuis le constructeur.' },
        { q: 'Que se passe-t-il si je change un prix ?', a: 'Il se met à jour sur votre site, car il vient du même catalogue.' },
      ],
    },
    'tienda-en-linea': {
      name: 'Boutique en ligne',
      short: 'Vendez en ligne avec votre inventaire réel.',
      eyebrow: 'Boutique en ligne',
      headline: 'Vendez en ligne avec l’inventaire que vous avez déjà.',
      lead: 'Votre catalogue publié comme boutique : panier, paiements en ligne, livraison ou cueillette, coupons et avis. Chaque commande arrive dans GO Admin, déduit le stock et est prête à facturer.',
      pains: [
        { pain: 'Vous gérez la boutique en ligne et l’inventaire séparément.', answer: 'Le stock est le même pour le magasin et la boutique en ligne.' },
        { pain: 'Les commandes arrivent par WhatsApp et se perdent.', answer: 'Chaque commande a un numéro, un statut et un responsable.' },
        { pain: 'Encaisser en ligne vous semble compliqué.', answer: 'Des passerelles de paiement de votre pays déjà connectées.' },
      ],
      features: [
        { title: 'Catalogue publié', text: 'Catégories, variantes, photos et prix issus de l’inventaire.' },
        { title: 'Panier et paiements', text: '{gateways} et plus encore.' },
        { title: 'Livraison ou cueillette', text: 'Frais de livraison, livraison gratuite dès un certain montant et commandes planifiées.' },
        { title: 'Coupons et promotions', text: 'Codes de rabais et comptes à rebours.' },
        { title: 'Commandes en temps réel', text: 'Confirmation, préparation, expédition et livraison.' },
        { title: 'Avis des clients', text: 'Évaluations vérifiées par achat, avec réponse.' },
      ],
      steps: [
        { title: 'Activez la boutique', text: 'Votre catalogue est déjà chargé.' },
        { title: 'Connectez les paiements', text: 'Choisissez votre passerelle.' },
        { title: 'Définissez les livraisons', text: 'Livraison, cueillette et tarifs.' },
        { title: 'Recevez des commandes', text: 'Elles arrivent dans l’ERP avec leur statut.' },
      ],
      highlights: ['Même inventaire que le magasin', 'Paiements en ligne {inCountry}', 'Livraison, cueillette et coupons'],
      faq: [
        { q: 'Quelles passerelles de paiement puis-je utiliser ?', a: '{gateways}, entre autres.' },
        { q: 'Est-ce adapté aux commandes de restaurant ?', a: 'Oui. Avec livraison ou cueillette, pourboires et commandes planifiées.' },
      ],
    },
    'motor-de-reservas': {
      name: 'Moteur de réservation',
      short: 'Réservations directes de chambres, de tables et de rendez-vous.',
      eyebrow: 'Moteur de réservation',
      headline: 'Des réservations directes, sans commissions d’intermédiaires.',
      lead: 'Vos clients réservent chambres, tables ou rendez-vous depuis votre site, avec la disponibilité réelle. Les réservations arrivent dans le calendrier GO Admin avec celles des canaux externes.',
      pains: [
        { pain: 'Vous dépendez de plateformes qui prennent une commission sur chaque réservation.', answer: 'Des réservations directes depuis votre propre site.' },
        { pain: 'Vous confirmez les réservations une à une par téléphone.', answer: 'Confirmation automatique par courriel ou WhatsApp.' },
        { pain: 'Les clients ne se présentent pas et vous perdez la table.', answer: 'Rappels, politiques d’annulation et dépôts.' },
      ],
      features: [
        { title: 'Chambres', text: 'Disponibilité et tarifs du PMS, avec extras.' },
        { title: 'Tables', text: 'Services, taille du groupe, zones et attribution de table.' },
        { title: 'Rendez-vous et cours', text: 'Agenda des services, des cours et des abonnements.' },
        { title: 'Dépôts et politiques', text: 'Acomptes, annulation et confirmation.' },
        { title: 'Rappels', text: 'Par courriel et WhatsApp avant l’arrivée.' },
        { title: 'Tout dans un calendrier', text: 'Directes et issues des canaux externes, sans chevauchements.' },
      ],
      steps: [
        { title: 'Définissez la disponibilité', text: 'Chambres, tables ou services.' },
        { title: 'Configurez les règles', text: 'Délai, groupes, dépôts.' },
        { title: 'Publiez', text: 'Sur votre site GO Admin.' },
        { title: 'Recevez', text: 'Des réservations confirmées dans votre calendrier.' },
      ],
      highlights: ['Chambres, tables et rendez-vous', 'Dépôts et rappels', 'Même calendrier que vos canaux'],
      faq: [
        { q: 'Est-ce que ça fonctionne avec Booking.com ?', a: 'Oui. Les réservations directes et celles des canaux partagent le même calendrier.' },
        { q: 'Puis-je demander un dépôt ?', a: 'Oui. Vous définissez s’il est fixe ou par personne.' },
      ],
    },

    // -----------------------------------------------------------------------
    // Données et IA
    // -----------------------------------------------------------------------
    reportes: {
      name: 'Rapports',
      short: 'Des tableaux de bord prêts pour décider.',
      eyebrow: 'Rapports et analytique',
      headline: 'Avez-vous vendu plus ou gagné plus ?',
      lead: 'Tableaux de bord des ventes, marges, comptes clients, inventaire et équipe, prêts dès le premier jour. Enregistrez vos vues et recevez des rapports planifiés par courriel.',
      pains: [
        { pain: 'Vous montez vos rapports dans Excel à chaque fin de mois.', answer: 'Des tableaux de bord mis à jour à chaque opération.' },
        { pain: 'Vous voyez les ventes, mais pas la marge.', answer: 'Ventes, coût et marge par produit et par site.' },
        { pain: 'Vous apprenez trop tard ce qui compte.', answer: 'Des alertes quand un indicateur franchit un seuil.' },
      ],
      features: [
        { title: 'Tableaux de bord par secteur', text: 'Ventes, inventaire, finances, clients et équipe.' },
        { title: 'Comparaisons', text: 'Par période, site, vendeur ou canal.' },
        { title: 'Rapports enregistrés', text: 'Vos filtres et colonnes, prêts à réutiliser.' },
        { title: 'Envois planifiés', text: 'Dans votre boîte courriel chaque jour, semaine ou mois.' },
        { title: 'Alertes', text: 'Quand quelque chose demande votre attention.' },
        { title: 'Exportez', text: 'Vers Excel et PDF.' },
      ],
      steps: [
        { title: 'Ouvrez votre tableau de bord', text: 'Il est déjà prêt.' },
        { title: 'Filtrez', text: 'Par date, site ou canal.' },
        { title: 'Enregistrez', text: 'Vos vues favorites.' },
        { title: 'Planifiez', text: 'Recevez le rapport sans le demander.' },
      ],
      highlights: ['Tableaux de bord prêts', 'Rapports planifiés', 'Alertes par indicateur'],
      faq: [
        { q: 'Puis-je voir plusieurs sites ensemble ?', a: 'Oui, et aussi les comparer entre eux.' },
        { q: 'Qui peut voir les rapports ?', a: 'Vous le définissez par rôle : chaque personne voit ce qui la concerne.' },
      ],
    },
    'inteligencia-artificial': {
      name: 'GO Admin IA',
      short: 'Posez vos questions à votre entreprise.',
      eyebrow: 'GO Admin IA',
      headline: 'Posez vos questions à votre entreprise.',
      lead: 'Écrivez comme vous parleriez à votre comptable. L’IA consulte vos ventes, votre inventaire et vos comptes clients, et répond avec des chiffres et des graphiques. Elle vous aide aussi avec des textes et des images pour vos produits.',
      pains: [
        { pain: 'Vous avez des données, mais pas le temps de les analyser.', answer: 'Des questions en langage courant et des réponses chiffrées.' },
        { pain: 'Rédiger les descriptions de produits vous prend des heures.', answer: 'Textes et images générés à partir de votre catalogue.' },
        { pain: 'Les questions comptables attendent le comptable.', answer: 'Un assistant comptable qui explique et suggère des écritures.' },
      ],
      features: [
        { title: 'Demandez simplement', text: '« Qu’est-ce qui s’est le plus vendu cette semaine ? » et recevez la réponse.' },
        { title: 'Des rapports à partir d’une question', text: 'Avec tableau et graphique prêts à partager.' },
        { title: 'Assistant comptable', text: 'Explications et suggestions sur vos mouvements.' },
        { title: 'Contenu pour les produits', text: 'Descriptions et images pour votre boutique.' },
        { title: 'Des agents qui suggèrent', text: 'Recommandations de réapprovisionnement et de recouvrement.' },
        { title: 'Crédits par forfait', text: '500, 2 000 ou 10 000 crédits par mois, avec recharges.' },
      ],
      steps: [
        { title: 'Ouvrez l’assistant', text: 'Depuis n’importe quel écran.' },
        { title: 'Posez votre question', text: 'Comme vous parleriez à une personne.' },
        { title: 'Vérifiez', text: 'Chiffres, tableau et graphique.' },
        { title: 'Agissez', text: 'Enregistrez le rapport ou créez la tâche.' },
      ],
      highlights: ['Des réponses avec vos données', 'Assistant comptable', 'Textes et images pour les produits'],
      faq: [
        { q: 'L’IA voit-elle les données d’autres entreprises ?', a: 'Non. Elle consulte uniquement l’information de votre organisation et respecte les permissions de chaque utilisateur.' },
        { q: 'Que sont les crédits d’IA ?', a: 'Chaque question ou génération consomme des crédits. Chaque forfait inclut une quantité mensuelle et vous pouvez en acheter davantage.' },
      ],
    },
  },

  solutions: {
    gastronomia: {
      name: 'Restaurants, bars et cafés',
      short: 'Tout ce qui sert à manger et à boire : tables, bar, comptoir et livraison.',
      types: [
        'Restaurants',
        'Casse-croûte et restauration rapide',
        'Bars et gastropubs',
        'Discothèques',
        'Cafés',
        'Boulangeries et pâtisseries',
        'Crèmeries et bars laitiers',
        'Camions de cuisine de rue',
        'Cuisines fantômes',
        'Traiteurs et événements',
        'Cafétérias et cantines',
      ],
      headline: 'De la commande à la cuisine, sans bouts de papier.',
      lead: 'Tables, bar ou comptoir ; des bons qui arrivent à chaque poste, des recettes qui déduisent les ingrédients et une caisse qui balance. Avec menu en ligne, commandes à livrer et réservations depuis votre site.',
      pains: [
        { pain: 'Les bons se perdent entre le bar et la cuisine.', answer: 'Des bons par poste avec leur statut à l’écran ou sur imprimante.' },
        { pain: 'Vous ne savez pas combien vous coûte chaque plat ou chaque verre.', answer: 'Des recettes qui déduisent les ingrédients et calculent le coût.' },
        { pain: 'Les commandes arrivent par WhatsApp, par applications et par téléphone.', answer: 'Les commandes de votre boutique en ligne et des applications de livraison au même endroit.' },
        { pain: 'Les additions ouvertes s’emmêlent en fin de quart.', answer: 'Additions par table ou par personne, séparables au paiement.' },
      ],
      day: [
        { moment: 'Avant d’ouvrir', title: 'Vous vérifiez stocks et production', text: 'Alertes sur ce qui s’épuise et ordres de production pour la cuisine ou le four.' },
        { moment: 'Heure de pointe', title: 'Tables, bar et comptoir', text: 'Encaissement rapide, additions séparées, pourboires et bons vers chaque poste.' },
        { moment: 'Toute la journée', title: 'Commandes en ligne', text: 'Livraisons et commandes à emporter depuis votre boutique, avec statut et responsable.' },
        { moment: 'À la fermeture', title: 'Vous fermez la journée', text: 'Comptage de caisse, ventes par serveur ou caissier, pertes et factures émises.' },
      ],
      channel: { title: 'Votre menu en ligne, avec commandes et réservations', text: 'Publiez votre menu avec photos, recevez des commandes à livrer ou à emporter et des réservations de table depuis votre site.' },
      features: [
        { title: 'Tables, bar ou comptoir', text: 'Plan de salle par zone, additions ouvertes ou vente rapide.' },
        { title: 'Modificateurs', text: 'Cuisson, ajouts et retraits d’ingrédients pour chaque produit.' },
        { title: 'Recettes et production', text: 'Coût par plat ou par verre et déduction des ingrédients.' },
        { title: 'Pourboires et frais', text: 'Pourboire suggéré, frais de service et droit d’entrée.' },
        { title: 'Plusieurs caisses et postes', text: 'Cuisine, bar, desserts ou plusieurs points de vente.' },
        { title: 'Pertes', text: 'Gaspillage et gratuités enregistrés avec motif.' },
        { title: 'Boutons rapides', text: 'Vos produits les plus vendus en un seul geste.' },
        { title: 'Plusieurs sites', text: 'Production centrale et transferts vers chaque point.' },
      ],
      faq: [
        { q: 'Est-ce adapté si je n’ai pas de tables, seulement un comptoir ?', a: 'Oui. Vous pouvez vendre au comptoir, aux tables ou combiner les deux dans le même établissement.' },
        { q: 'Puis-je afficher les bons à l’écran en cuisine ?', a: 'Oui, ou sur des imprimantes par poste : cuisine, bar ou desserts.' },
        { q: 'Est-ce que je reçois les commandes des applications de livraison ?', a: 'Il existe des connecteurs avec des applications de livraison ; consultez la page Intégrations pour voir lesquels sont disponibles.' },
        { q: 'Puis-je produire dans un site et vendre dans d’autres ?', a: 'Oui, avec des ordres de production et des transferts entre entrepôts.' },
      ],
    },
    hospedaje: {
      name: 'Hôtels, hébergement et tourisme',
      short: 'Tout ce qui se réserve à la nuit ou à la journée : chambres, chalets et espaces.',
      types: [
        'Hôtels',
        'Auberges',
        'Chalets',
        'Prêt-à-camper et glamping',
        'Fermettes et maisons de vacances',
        'Appartements touristiques',
        'Motels',
        'Clubs et centres de villégiature',
        'Gîtes et écohôtels',
        'Agences et forfaits touristiques',
      ],
      headline: 'Votre hébergement complet, sans réservations en double.',
      lead: 'Calendrier d’occupation, arrivées et départs, folios par client, ménage et entretien, et synchronisation avec Booking.com, Expedia et Airbnb. Avec votre propre moteur de réservation sur votre site.',
      pains: [
        { pain: 'Des surréservations entre les portails et la réception.', answer: 'Disponibilité synchronisée sur tous les canaux.' },
        { pain: 'Vous payez une commission sur presque toutes vos réservations.', answer: 'Moteur de réservations directes sur votre propre site.' },
        { pain: 'Les consommations des clients sont oubliées au départ.', answer: 'Folios avec les frais du restaurant, du minibar et des services.' },
        { pain: 'Les réservations arrivent par WhatsApp et se notent dans un cahier.', answer: 'Un calendrier unique, avec acomptes et confirmation.' },
      ],
      day: [
        { moment: 'Le matin', title: 'Vous vérifiez arrivées et départs', text: 'L’équipe de ménage sait quelle chambre, quel chalet ou quel espace préparer.' },
        { moment: 'Midi', title: 'Départs', text: 'Folio fermé et facture envoyée au client.' },
        { moment: 'L’après-midi', title: 'Arrivées', text: 'Enregistrement des clients et attribution de l’espace.' },
        { moment: 'Le soir', title: 'Nouvelles réservations', text: 'Elles arrivent des portails et de votre site dans le même calendrier.' },
      ],
      channel: { title: 'Moteur de réservation directe', text: 'Votre site avec photos, tarifs et disponibilité réelle pour réserver et payer l’acompte sans intermédiaires.' },
      features: [
        { title: 'Calendrier d’occupation', text: 'Par type de chambre, de chalet ou d’espace, avec blocages.' },
        { title: 'Synchronisation avec les portails', text: 'Booking.com, Expedia, Airbnb et iCal.' },
        { title: 'Tarifs flexibles', text: 'Par saison, nuit, journée ou nombre de personnes.' },
        { title: 'Ménage et entretien', text: 'Tâches classées par priorité selon les arrivées et les départs.' },
        { title: 'Folios et consommations', text: 'Restaurant, minibar et services portés au compte.' },
        { title: 'Groupes et entreprises', text: 'Réservations de groupe, forfaits et comptes d’entreprise.' },
        { title: 'Acomptes en ligne', text: 'Paiements avec les passerelles intégrées.' },
        { title: 'Clients fidèles', text: 'Historique, préférences et communication.' },
      ],
      faq: [
        { q: 'Est-ce adapté aux chalets, au glamping ou aux fermettes ?', a: 'Oui. Vous configurez vos espaces, types, capacités et tarifs selon votre fonctionnement, qu’il s’agisse de chambres ou d’unités indépendantes.' },
        { q: 'Et si j’ai aussi un restaurant ou un spa ?', a: 'Les consommations se vendent depuis le point de vente et sont portées au folio du client.' },
        { q: 'Puis-je encaisser des acomptes ?', a: 'Oui, depuis le moteur de réservation avec paiements en ligne.' },
      ],
    },
    'espacios-y-eventos': {
      name: 'Espaces, terrains et événements',
      short: 'Tout ce qui se réserve à l’heure : terrains, salles, clubs et activités.',
      types: [
        'Terrains synthétiques',
        'Clubs sociaux et sportifs',
        'Salles de réception',
        'Espaces de cotravail et salles de réunion',
        'Parcs récréatifs',
        'Piscines et centres récréatifs',
        'Jeux d’évasion',
        'Studios d’enregistrement et de photographie',
        'Visites et expériences',
      ],
      headline: 'Vos espaces réservés, sans chevauchements.',
      lead: 'Réservations à l’heure ou à la journée, acomptes en ligne, entrées et consommations au même endroit. Vos clients voient la disponibilité réelle sur votre site et réservent eux-mêmes.',
      pains: [
        { pain: 'Deux groupes arrivent sur le même terrain à la même heure.', answer: 'Un calendrier par espace avec la disponibilité réelle.' },
        { pain: 'Des réservations sans présence et un espace qui reste vide.', answer: 'Acompte en ligne et confirmation automatique.' },
        { pain: 'Le casse-croûte, la location et les entrées s’encaissent séparément.', answer: 'Tout dans la même caisse et dans le même rapport.' },
      ],
      day: [
        { moment: 'Le matin', title: 'Vous vérifiez l’agenda', text: 'Espaces réservés, acomptes reçus et ce qu’il reste à encaisser.' },
        { moment: 'Toute la journée', title: 'Réservations depuis votre site', text: 'Vos clients choisissent l’espace, la date et l’heure, et paient l’acompte.' },
        { moment: 'Pendant l’utilisation', title: 'Consommations et entrées', text: 'Boissons, location d’équipement et entrées au point de vente.' },
        { moment: 'À la fermeture', title: 'Fermeture', text: 'Occupation par espace, ventes et factures.' },
      ],
      channel: { title: 'Réservation d’espaces en ligne', text: 'Vos clients réservent un terrain, une salle ou une activité à l’heure depuis votre site et paient l’acompte.' },
      features: [
        { title: 'Réservations à l’heure', text: 'Plages horaires par espace, avec durée minimale.' },
        { title: 'Tarifs par horaire', text: 'Des prix différents aux heures de pointe, la fin de semaine ou les jours fériés.' },
        { title: 'Acomptes et dépôts', text: 'Paiements en ligne à la réservation.' },
        { title: 'Consommations sur place', text: 'Casse-croûte, location d’équipement et entrées.' },
      ],
      faq: [
        { q: 'Puis-je avoir plusieurs terrains ou salles ?', a: 'Oui. Chaque espace a son calendrier, sa capacité et son tarif.' },
        { q: 'Est-ce adapté aux clubs avec membres ?', a: 'Oui. Les membres sont enregistrés comme clients et vous pouvez combiner réservations et abonnements avec la solution Centres d’entraînement, écoles et abonnements.' },
      ],
    },
    comercio: {
      name: 'Boutiques et commerce',
      short: 'Tout ce qui vend des produits : en magasin, en ligne ou en gros.',
      types: [
        'Dépanneurs et épiceries',
        'Vêtements, chaussures et accessoires',
        'Quincailleries',
        'Pharmacies',
        'Électronique et cellulaires',
        'Papeteries et librairies',
        'Animaleries',
        'Cosmétiques et beauté',
        'Meubles et décoration',
        'Distributeurs et grossistes',
        'Boutiques en ligne seulement',
      ],
      headline: 'Vendez en magasin et en ligne avec un seul inventaire.',
      lead: 'Point de vente avec code-barres, variantes, prix par liste, inventaire par site, boutique en ligne connectée et facturation depuis la même vente.',
      pains: [
        { pain: 'Vous vendez en ligne un article qui n’est plus en magasin.', answer: 'Un seul inventaire pour le magasin et la boutique en ligne.' },
        { pain: 'Gérer tailles, couleurs ou formats, c’est le chaos.', answer: 'Des variantes avec leur propre stock et leur code-barres.' },
        { pain: 'Vous ne savez pas quels produits tournent et lesquels dorment.', answer: 'Rapports de rotation et de marge par produit.' },
        { pain: 'Vos clients grossistes paient des prix différents.', answer: 'Listes de prix et crédit par client.' },
      ],
      day: [
        { moment: 'À l’ouverture', title: 'Vous vérifiez les stocks', text: 'Stock par site et alertes de réapprovisionnement.' },
        { moment: 'Pendant la journée', title: 'Vous vendez au comptoir', text: 'Code-barres, paiements combinés et facture.' },
        { moment: 'L’après-midi', title: 'Les commandes en ligne arrivent', text: 'Vous préparez, expédiez et facturez.' },
        { moment: 'À la fermeture', title: 'Fermeture et achats', text: 'Ventes par vendeur et par canal, et commandes aux fournisseurs.' },
      ],
      channel: { title: 'Votre boutique en ligne, prête', text: 'Votre catalogue publié avec panier, paiements, livraisons et coupons, relié au même inventaire.' },
      features: [
        { title: 'Variantes', text: 'Tailles, couleurs, formats et références.' },
        { title: 'Code-barres', text: 'À la vente, à l’achat et lors des comptages.' },
        { title: 'Listes de prix', text: 'Détail, gros ou par client.' },
        { title: 'Multisite', text: 'Inventaire et prix par succursale.' },
        { title: 'Achats et fournisseurs', text: 'Bons de commande et réception de marchandise.' },
        { title: 'Lots et dates d’expiration', text: 'Pour les aliments, les médicaments et les cosmétiques.' },
        { title: 'Promotions', text: 'Rabais, coupons et saisons.' },
        { title: 'Garanties', text: 'Numéros de série et réclamations.' },
      ],
      faq: [
        { q: 'Puis-je utiliser un lecteur de code-barres ?', a: 'Oui, au point de vente, pour les achats et lors des comptages.' },
        { q: 'Est-ce adapté à la vente en gros ?', a: 'Oui : listes de prix, soumissions, crédit et comptes clients par client.' },
        { q: 'Puis-je vendre seulement en ligne, sans magasin ?', a: 'Oui. La boutique en ligne fonctionne seule, avec le même inventaire et la même facturation.' },
      ],
    },
    'belleza-y-salud': {
      name: 'Beauté, santé et bien-être',
      short: 'Tout ce qui fonctionne sur rendez-vous : services, professionnels et agenda.',
      types: [
        'Salons de coiffure et barbiers',
        'Spas et centres d’esthétique',
        'Ongles et cils',
        'Cabinets médicaux',
        'Dentisterie',
        'Physiothérapie',
        'Psychologie et thérapies',
        'Cliniques vétérinaires',
        'Optométristes et lunetteries',
        'Salons de tatouage',
      ],
      headline: 'Votre agenda plein, vos clients qui reviennent.',
      lead: 'Rendez-vous par professionnel, rappels, historique de chaque client, vente de services et de produits à la même caisse, et un site où vos clients prennent rendez-vous eux-mêmes.',
      pains: [
        { pain: 'Les rendez-vous se prennent par WhatsApp et se chevauchent.', answer: 'Agenda par professionnel et par service, sans chevauchements.' },
        { pain: 'Des clients qui ne se présentent pas à leur rendez-vous.', answer: 'Rappels automatiques et acompte facultatif.' },
        { pain: 'Vous ne savez pas combien vend chaque professionnel.', answer: 'Ventes et services par professionnel dans vos rapports.' },
      ],
      day: [
        { moment: 'À l’ouverture', title: 'Vous vérifiez l’agenda', text: 'Rendez-vous du jour par professionnel et par salle.' },
        { moment: 'Pendant la journée', title: 'Vous servez et encaissez', text: 'Services et produits sur la même facture.' },
        { moment: 'Toute la journée', title: 'Nouveaux rendez-vous en ligne', text: 'Vos clients choisissent le service, le professionnel et l’heure.' },
        { moment: 'À la fermeture', title: 'Suivi', text: 'Ventes par professionnel et clients à recontacter.' },
      ],
      channel: { title: 'Prise de rendez-vous sur votre site', text: 'Vos clients choisissent le service, le professionnel et l’heure, et reçoivent leur confirmation.' },
      features: [
        { title: 'Agenda par professionnel', text: 'Horaires, services et salles de chaque personne.' },
        { title: 'Rappels', text: 'Par courriel ou WhatsApp avant chaque rendez-vous.' },
        { title: 'Historique du client', text: 'Services, achats et notes de chaque visite.' },
        { title: 'Services et produits', text: 'Sur la même facture, avec l’inventaire des fournitures.' },
      ],
      faq: [
        { q: 'Mes clients peuvent-ils prendre rendez-vous eux-mêmes ?', a: 'Oui, depuis votre site, en choisissant le service, le professionnel et une heure disponible.' },
        { q: 'Puis-je vendre des forfaits de séances ?', a: 'Oui, comme produits ou forfaits que le client utilise sur plusieurs visites.' },
      ],
    },
    'gimnasios-y-academias': {
      name: 'Centres d’entraînement, écoles et abonnements',
      short: 'Tout ce qui vend des forfaits : membres, cours, accès et renouvellements.',
      types: [
        'Centres d’entraînement',
        'Entraînement fonctionnel',
        'Yoga, pilates et danse',
        'Écoles de langues et de formation',
        'Écoles de sport',
        'Clubs avec membres',
        'Arts martiaux',
        'Centres aquatiques',
      ],
      headline: 'Abonnements à jour, cours complets.',
      lead: 'Forfaits d’abonnement, suspensions, contrôle d’accès par code QR, cours avec places limitées et réservations, et paiements récurrents. Avec votre propre site pour vendre des forfaits et réserver des cours.',
      pains: [
        { pain: 'Des membres qui entrent avec un abonnement expiré.', answer: 'Accès validé selon le statut de l’abonnement.' },
        { pain: 'Les cours débordent ou restent vides.', answer: 'Places limitées et réservations depuis le cellulaire.' },
        { pain: 'Encaisser les mensualités, c’est courir après les gens.', answer: 'Rappels et paiements en ligne.' },
      ],
      day: [
        { moment: 'À l’ouverture', title: 'Entrées', text: 'Enregistrement par code QR et alertes d’expiration.' },
        { moment: 'Pendant la journée', title: 'Cours', text: 'Présence de ceux qui ont réservé.' },
        { moment: 'Midi', title: 'Ventes', text: 'Forfaits, produits et renouvellements.' },
        { moment: 'À la fermeture', title: 'Suivi', text: 'Membres dont l’abonnement arrive à échéance et membres inactifs.' },
      ],
      channel: { title: 'Réservation de cours et vente de forfaits', text: 'Vos membres et vos élèves réservent leurs cours et renouvellent leur forfait depuis votre site.' },
      features: [
        { title: 'Forfaits et abonnements', text: 'Mensuels, trimestriels, annuels ou par séances.' },
        { title: 'Suspensions', text: 'Des pauses avec date de réactivation.' },
        { title: 'Accès par code QR', text: 'Enregistrement et dispositifs de contrôle d’accès.' },
        { title: 'Cours et places', text: 'Horaires, instructeurs et réservations.' },
      ],
      faq: [
        { q: 'Est-ce adapté aux écoles ou aux cours, pas seulement aux centres d’entraînement ?', a: 'Oui. Les cours se gèrent comme des forfaits avec horaires, places et présences.' },
        { q: 'Puis-je faire payer des séances à l’unité ?', a: 'Oui. Vous pouvez vendre des forfaits par nombre de séances ou des entrées individuelles.' },
      ],
    },
    movilidad: {
      name: 'Stationnements, transport et mobilité',
      short: 'Tout ce qui déplace ou garde des véhicules : places, trajets, billets et envois.',
      types: [
        'Stationnements',
        'Lave-autos',
        'Transport de passagers',
        'Transport nolisé et touristique',
        'Colis et messagerie',
        'Location de véhicules',
        'Garages et centres de service automobile',
      ],
      headline: 'Chaque véhicule, chaque minute, facturé.',
      lead: 'Entrées et sorties par plaque avec tarif au temps, abonnements mensuels, trajets et billets avec siège, envois avec bordereau, parc de véhicules et chauffeurs, synchronisés avec la caisse et la facturation.',
      pains: [
        { pain: 'Des billets papier qui se perdent.', answer: 'Entrée enregistrée par plaque avec billet imprimé ou numérique.' },
        { pain: 'Des montants mal calculés à la sortie.', answer: 'Tarifs à la minute, à l’heure ou à la journée appliqués automatiquement.' },
        { pain: 'Des sièges vendus en double sur un même trajet.', answer: 'Attribution de siège par trajet.' },
        { pain: 'Des documents du parc de véhicules qui expirent.', answer: 'Véhicules et permis avec alertes.' },
      ],
      day: [
        { moment: 'À l’ouverture', title: 'Vous ouvrez le quart', text: 'Caisse, occupation initiale et départs du jour.' },
        { moment: 'Heure de pointe', title: 'Entrées et ventes', text: 'Enregistrement par plaque, billets au guichet et en ligne.' },
        { moment: 'L’après-midi', title: 'Envois et départs', text: 'Bordereaux, livraisons et montants calculés.' },
        { moment: 'À la fermeture', title: 'Fermeture du quart', text: 'Comptage de caisse, occupation et recettes par trajet ou par opérateur.' },
      ],
      channel: { title: 'Tarifs, abonnements et billets en ligne', text: 'Publiez tarifs, horaires et emplacement ; vendez des abonnements mensuels ou des billets avec siège depuis votre site.' },
      features: [
        { title: 'Plan des places', text: 'Zones et types de véhicules.' },
        { title: 'Tarifs au temps', text: 'À la minute, à l’heure, à la journée ou par fraction.' },
        { title: 'Abonnements mensuels', text: 'Abonnements avec véhicules autorisés.' },
        { title: 'Trajets et billets', text: 'Horaires, arrêts et plan des sièges.' },
        { title: 'Envois', text: 'Bordereaux, manifestes et preuve de livraison.' },
        { title: 'Parc de véhicules', text: 'Véhicules, chauffeurs et incidents.' },
        { title: 'Quarts', text: 'Fermeture par opérateur.' },
        { title: 'Services au véhicule', text: 'Lavage, stationnement et services sur la même facture.' },
      ],
      faq: [
        { q: 'Puis-je avoir plusieurs tarifs selon le véhicule ?', a: 'Oui, par type de véhicule et par horaire.' },
        { q: 'Gérez-vous les colis ?', a: 'Oui : bordereaux, manifestes, tentatives de livraison et preuve de livraison.' },
      ],
    },
    servicios: {
      name: 'Services et entreprises',
      short: 'Tout ce qui vend un savoir ou du travail : projets, soumissions et encaissements.',
      types: [
        'Agences et cabinets-conseils',
        'Comptables et avocats',
        'Construction et entretien',
        'Ateliers et service technique',
        'Éducation et écoles',
        'Entreprises de logiciels',
        'Agences immobilières',
        'Sécurité et entretien ménager',
        'Fondations et OSBL',
      ],
      headline: 'Du premier contact au dernier paiement.',
      lead: 'Occasions d’affaires, soumissions, agenda, projets avec tâches et heures, facturation, comptabilité et comptes clients, au même endroit.',
      pains: [
        { pain: 'Vous faites vos soumissions dans Word et perdez le suivi.', answer: 'Des soumissions liées à l’entonnoir de vente.' },
        { pain: 'Vous ne savez pas si un projet est rentable.', answer: 'Heures et coûts par projet.' },
        { pain: 'Les comptes clients s’accumulent.', answer: 'Échéances et rappels de paiement.' },
      ],
      day: [
        { moment: 'Le matin', title: 'L’agenda du jour', text: 'Rendez-vous, tâches et réunions.' },
        { moment: 'Midi', title: 'Vous préparez des soumissions', text: 'Depuis l’occasion, avec suivi.' },
        { moment: 'L’après-midi', title: 'Vous réalisez', text: 'Projets, jalons et heures saisies.' },
        { moment: 'À la fermeture', title: 'Vous encaissez', text: 'Facture et rappel automatique.' },
      ],
      channel: { title: 'Site avec agenda et formulaire', text: 'Présentez vos services, recevez des demandes et laissez vos clients prendre rendez-vous.' },
      features: [
        { title: 'Soumissions', text: 'Avec modèles et approbation.' },
        { title: 'Projets', text: 'Jalons, tâches et équipe.' },
        { title: 'Heures', text: 'Saisie du temps par tâche.' },
        { title: 'Comptes clients', text: 'Échéances et rappels.' },
      ],
      faq: [
        { q: 'Est-ce adapté aux entreprises avec facturation récurrente ?', a: 'Oui : forfaits, abonnements et facturation périodique.' },
        { q: 'Mon comptable peut-il y accéder ?', a: 'Oui, avec un rôle qui ne voit que la comptabilité et les rapports.' },
      ],
    },
  },

  integrations: {
    groups: {
      pagos: {
        name: 'Paiements et banques',
        text: 'Encaissez en ligne, par code QR ou par terminal de paiement, et rapprochez vos comptes.',
        items: {
          'Wompi': 'Paiements en ligne.',
          'PSE': 'Prélèvement depuis un compte bancaire.',
          'Nequi': 'Paiements depuis le portefeuille numérique.',
          'DaviPlata': 'Paiements depuis le portefeuille numérique.',
          'SPEI': 'Virements instantanés.',
          'OXXO Pay': 'Paiements comptant en magasin.',
          'Conekta': 'Cartes et paiements en ligne.',
          'PayU': 'Cartes et moyens de paiement locaux.',
          'Mercado Pago': 'Paiements en ligne et par code QR.',
          'Bold': 'Terminaux de paiement et liens de paiement.',
          'Bre-B': 'Paiements instantanés du Banco de la República.',
          'Bancolombia': 'Comptes et mouvements.',
          'Redeban': 'Terminaux de paiement et acquisition.',
          'Stripe': 'Paiements internationaux.',
          'PayPal': 'Paiements internationaux.',
          'Venmo': 'Paiements entre particuliers.',
          'Cash App': 'Paiements entre particuliers.',
          'Zelle': 'Virements bancaires.',
        },
      },
      reservas: {
        name: 'Canaux de réservation',
        text: 'Disponibilité et réservations synchronisées avec votre calendrier.',
        items: {
          'Booking.com': 'Réservations, tarifs et disponibilité.',
          'Expedia Group': 'Réservations et disponibilité.',
          'Airbnb': 'Calendrier et réservations.',
          'Google Vacation Rentals': 'Présence sur Google.',
          'TripAdvisor': 'Présence et avis.',
        },
      },
      domicilios: {
        name: 'Livraisons et expéditions',
        text: 'Commandes des applications et bordereaux des transporteurs.',
        items: {
          'Rappi': 'Commandes à livrer.',
          'Uber Eats': 'Commandes à livrer.',
          'iFood': 'Commandes à livrer.',
          'Coordinadora': 'Bordereaux et suivi.',
          'Servientrega': 'Bordereaux et suivi.',
          'Interrapidísimo': 'Bordereaux et suivi.',
          'Envía': 'Estimation des frais et bordereaux.',
        },
      },
      mensajeria: {
        name: 'Messagerie',
        text: 'Échangez avec vos clients et envoyez-leur des notifications.',
        items: {
          'WhatsApp Business': 'Clavardage, campagnes et notifications.',
          'Twilio': 'Textos et appels.',
          'SendGrid': 'Courriels transactionnels.',
        },
      },
      marketing: {
        name: 'Réseaux sociaux et publicité',
        text: 'Catalogue, messages et campagnes.',
        items: {
          'Meta (Facebook, Instagram)': 'Messages et catalogue.',
          'TikTok Business': 'Catalogue et campagnes.',
          'Google Ads': 'Conversions et campagnes.',
        },
      },
    },
    developer: [
      { title: 'API', text: 'Consultez et créez des données de votre organisation avec des clés d’accès.' },
      { title: 'Webhooks', text: 'Recevez des événements quand quelque chose se passe : une vente, une réservation, un paiement.' },
      { title: 'Synchronisations', text: 'Des tâches planifiées avec un journal de chaque exécution.' },
    ],
  },
}
