import {
  BarChart3,
  BedDouble,
  Bell,
  BookOpen,
  Bot,
  Briefcase,
  Building2,
  Bus,
  Calculator,
  Calendar,
  DatabaseBackup,
  Dumbbell,
  FileCheck,
  GraduationCap,
  HeartHandshake,
  History,
  KeyRound,
  LayoutDashboard,
  LockKeyhole,
  Mail,
  MapPin,
  MessageCircle,
  Package,
  Plug,
  QrCode,
  Receipt,
  Rocket,
  ShieldCheck,
  ShoppingCart,
  Sparkles,
  SquareParking,
  Store,
  TrendingUp,
  UserRoundCheck,
  Users,
  Utensils,
  Wallet,
  Workflow,
  type LucideProps,
} from 'lucide-react'
import type { IconName } from '@/lib/site'

const MAP: Record<IconName, React.ComponentType<LucideProps>> = {
  cart: ShoppingCart,
  package: Package,
  receipt: Receipt,
  calculator: Calculator,
  users: Users,
  'user-check': UserRoundCheck,
  chart: BarChart3,
  bot: Bot,
  bed: BedDouble,
  utensils: Utensils,
  store: Store,
  dumbbell: Dumbbell,
  parking: SquareParking,
  bus: Bus,
  briefcase: Briefcase,
  bell: Bell,
  calendar: Calendar,
  plug: Plug,
  shield: ShieldCheck,
  lock: LockKeyhole,
  building: Building2,
  layout: LayoutDashboard,
  message: MessageCircle,
  book: BookOpen,
  'heart-handshake': HeartHandshake,
  graduation: GraduationCap,
  mail: Mail,
  database: DatabaseBackup,
  'map-pin': MapPin,
  trending: TrendingUp,
  sparkles: Sparkles,
  rocket: Rocket,
  key: KeyRound,
  workflow: Workflow,
  'file-check': FileCheck,
  qr: QrCode,
  wallet: Wallet,
  history: History,
}

/** Ícono de trazo (Manual › Iconografía: 1,5 px sobre grilla de 24 px, remates redondeados). */
export function Icon({ name, ...props }: { name: IconName } & LucideProps) {
  const Cmp = MAP[name]
  return <Cmp strokeWidth={1.5} aria-hidden {...props} />
}
