/**
 * English catalog: product categories, products, solutions and integrations.
 * Same shape, keys, order and list lengths as the Spanish base in lib/catalog.
 */
import type { CatalogText } from '../types'

export const catalog: CatalogText = {
  categories: {
    operacion: { name: 'Operations', text: 'What happens at the register, in the warehouse and in the rooms.' },
    finanzas: { name: 'Finance and team', text: 'Invoices, accounts and payroll up to date.' },
    clientes: { name: 'Customers', text: 'Every conversation and every sale, in one history.' },
    canales: { name: 'Digital channels', text: 'Your business online from day one.' },
    inteligencia: { name: 'Insights and AI', text: 'Clear answers to help you decide.' },
  },

  products: {
    // -----------------------------------------------------------------------
    // Operations
    // -----------------------------------------------------------------------
    'ventas-pos': {
      name: 'Sales and point of sale',
      short: 'Register, tables, kitchen tickets and payments.',
      eyebrow: 'Sales & POS',
      headline: 'Get paid without lines or notebooks.',
      lead: 'A point of sale for stores, restaurants and gyms. Every sale updates inventory, is ready to invoice and shows up in your reports.',
      pains: [
        { pain: 'At closing, the register doesn’t balance and you don’t know why.', answer: 'Cash count by payment method, with differences explained at closing.' },
        { pain: 'Table orders get lost between the bar and the kitchen.', answer: 'Kitchen tickets sent to each station, with real-time status.' },
        { pain: 'You sell something that’s no longer in stock.', answer: 'Stock goes down with every sale and warns you before it runs out.' },
      ],
      features: [
        { title: 'Register opening and closing', text: 'Opening float, cash movements, cash count and count by denomination.' },
        { title: 'Tables and kitchen tickets', text: 'Floor plan by area, split checks, tips and service charges.' },
        { title: 'Every payment method', text: 'Cash, card, bank transfer and QR payments in the same sale.' },
        { title: 'Promotions and coupons', text: 'Discount rules, coupons and prices by list or location.' },
        { title: 'Orderly returns', text: 'Return reasons, credit note and restocking.' },
        { title: 'Printers and terminals', text: 'Receipts, tickets by station and several registers per location.' },
      ],
      steps: [
        { title: 'Open the register', text: 'Record the opening float and who’s on shift.' },
        { title: 'Sell', text: 'Search by name or barcode, and take one or more payment methods.' },
        { title: 'Invoice', text: 'Issue the invoice or receipt from the same sale.' },
        { title: 'Close', text: 'The cash count compares what you counted with what you sold.' },
      ],
      highlights: ['Sales by location and cashier', 'Tickets to kitchen and bar', 'Invoicing in the same flow'],
      faq: [
        { q: 'Does it work on a tablet or phone?', a: 'Yes. GO Admin runs in the browser on your computer, tablet or phone.' },
        { q: 'Can I have several registers at the same location?', a: 'Yes. Each register has its own opening, movements and closing.' },
        { q: 'Does it connect to receipt and kitchen printers?', a: 'Yes. You assign printers by station so each area gets its own orders.' },
      ],
    },
    inventario: {
      name: 'Inventory',
      short: 'Stock by warehouse, batches and transfers.',
      eyebrow: 'Inventory',
      headline: 'Know what you have and where.',
      lead: 'Stock by warehouse and branch, costs, batches and transfers. Every sale subtracts and every purchase adds, with no spreadsheets.',
      pains: [
        { pain: 'You count your inventory and it never matches the system.', answer: 'Cycle counts, adjustments with a reason and a stock ledger for every movement.' },
        { pain: 'You don’t know the real cost of what you sell.', answer: 'Average cost and FIFO updated with every purchase.' },
        { pain: 'You move goods between locations and lose track.', answer: 'Transfers with dispatch, in-transit and receipt, with differences recorded.' },
      ],
      features: [
        { title: 'Complete catalog', text: 'Category tree, variants (size, color), images, units and barcodes.' },
        { title: 'Real-time stock', text: 'Stock by warehouse and branch, with low-stock alerts.' },
        { title: 'Purchasing and suppliers', text: 'Purchase orders, receiving and a link to accounts payable.' },
        { title: 'Batches and serial numbers', text: 'Expiration dates, warranties and traceability by serial number.' },
        { title: 'Recipes and production', text: 'Deduct ingredients when you sell a dish or produce a batch.' },
        { title: 'Stock ledger and adjustments', text: 'History of every movement: who, when and why.' },
      ],
      steps: [
        { title: 'Import your catalog', text: 'Upload products and stock from Excel.' },
        { title: 'Set warehouses and minimums', text: 'By location and by product.' },
        { title: 'Operate', text: 'Sales, purchases and transfers move stock on their own.' },
        { title: 'Count and adjust', text: 'Cycle counts with differences explained.' },
      ],
      highlights: ['Multiple warehouses and locations', 'Variants and barcodes', 'Average cost and FIFO'],
      faq: [
        { q: 'Can I manage sizes and colors?', a: 'Yes. You create variant types, and each combination has its own stock and code.' },
        { q: 'Does it work for restaurants?', a: 'Yes. With recipes, every dish sold deducts its ingredients.' },
        { q: 'How do I load my opening inventory?', a: 'You import it from Excel, and we help you with the first upload.' },
      ],
    },
    hoteleria: {
      name: 'Hospitality (PMS)',
      short: 'Bookings, check-in, folios and channels.',
      eyebrow: 'Hospitality',
      headline: 'Bookings and rooms with no overlaps.',
      lead: 'Occupancy calendar, check-in and check-out, guest folios, rates and connections to channels like Booking.com and Expedia.',
      pains: [
        { pain: 'A room sold twice on different channels.', answer: 'Availability synced with your booking channels.' },
        { pain: 'Guest charges end up on paper.', answer: 'Folios with charges from the restaurant, minibar and services.' },
        { pain: 'Housekeeping doesn’t know which rooms to clean first.', answer: 'Cleaning and maintenance tasks based on departures and arrivals.' },
      ],
      features: [
        { title: 'Booking calendar', text: 'View by room type, with blocks and groups.' },
        { title: 'Check-in and check-out', text: 'Guest registration and departure with a closed folio.' },
        { title: 'Split folios', text: 'Separate charges by guest or company.' },
        { title: 'Rates and extras', text: 'Seasonal rates, packages and add-on services.' },
        { title: 'Channel manager', text: 'Booking.com, Expedia, Airbnb and iCal calendars.' },
        { title: 'Housekeeping', text: 'Cleaning tasks and maintenance orders.' },
      ],
      steps: [
        { title: 'Set up rooms', text: 'Types, spaces, rates and services.' },
        { title: 'Connect channels', text: 'Map your room types to each channel.' },
        { title: 'Receive bookings', text: 'From channels, your booking engine or the front desk.' },
        { title: 'Invoice the stay', text: 'The folio becomes an invoice at checkout.' },
      ],
      highlights: ['Your own booking engine', 'Booking.com and Expedia', 'Folios and invoicing'],
      faq: [
        { q: 'Does it connect to Booking.com?', a: 'Yes. You map your room types and rates, and bookings arrive in your calendar.' },
        { q: 'Can I charge restaurant consumption to the room?', a: 'Yes. Point-of-sale charges can go to the guest’s folio.' },
      ],
    },

    // -----------------------------------------------------------------------
    // Finance and team
    // -----------------------------------------------------------------------
    'facturacion-electronica': {
      name: '{invoicing}',
      short: 'Invoices validated by {theAuthority}, straight from the sale.',
      eyebrow: '{invoicing}',
      headline: 'Invoice right where you sell.',
      lead: 'Issue invoices, credit notes and supporting documents validated by {theAuthority} from the point of sale or from finance, and check their status in one place.',
      pains: [
        { pain: 'You invoice in another program and type everything twice.', answer: 'The invoice comes from the sale, with customer, products and taxes.' },
        { pain: 'You don’t know whether {theAuthority} accepted or rejected a document.', answer: 'Status of every document, with the error explained if there is one.' },
        { pain: 'Credit notes and returns get tangled.', answer: 'Credit notes linked to the invoice and to the return.' },
      ],
      features: [
        { title: 'Sales invoice', text: 'Numbering, authorizations and email delivery to your customer.' },
        { title: 'Credit and debit notes', text: 'Linked to the original invoice and to returns.' },
        { title: 'Supporting document', text: 'For purchases from suppliers who aren’t required to invoice.' },
        { title: 'Taxes and withholdings', text: '{taxes} configurable by product and customer.' },
        { title: 'Status with {theAuthority}', text: '{docId}, QR code and validation response for every document.' },
        { title: 'Customer lookup', text: 'Your customer’s tax details, to avoid errors.' },
      ],
      steps: [
        { title: 'Get set up', text: 'Configure your numbering authorization and signing certificate.' },
        { title: 'Sell', text: 'From the POS, a quote or finance.' },
        { title: 'Issue', text: 'The document is validated and sent to your customer.' },
        { title: 'Check', text: 'Status, PDF and XML always at hand.' },
      ],
      highlights: ['Included in every plan', 'Invoices, notes and supporting documents', 'Real-time status with {theAuthority}'],
      faq: [
        { q: 'Do I need a digital certificate?', a: 'Yes, to sign documents. If you don’t have one, you can get it as an add-on.' },
        { q: 'Can I invoice from my phone?', a: 'Yes. Invoicing works in the browser on any device.' },
      ],
      variants: {
        noEInvoice: {
          short: 'Invoices with your country’s taxes.',
          lead: 'Issue invoices and credit notes with {taxes} from the point of sale or from finance, and send them to your customer. {einvoiceNote}',
          pains: [
            { pain: 'You invoice in another program and type everything twice.', answer: 'The invoice comes from the sale, with customer, products and taxes.' },
            { pain: 'You calculate taxes by hand on every invoice.', answer: '{taxes} set up by product and customer.' },
            { pain: 'Credit notes and returns get tangled.', answer: 'Credit notes linked to the invoice and to the return.' },
          ],
          features: [
            { title: 'Sales invoice', text: 'Numbering, PDF and email delivery to your customer.' },
            { title: 'Credit and debit notes', text: 'Linked to the original invoice and to returns.' },
            { title: 'Multiple currencies', text: 'Invoices in your currency and others, with exchange rates.' },
            { title: 'Your country’s taxes', text: '{taxes} configurable by product and customer.' },
            { title: 'Tax details', text: 'Identify your customers with {taxId} and your country’s documents.' },
            { title: 'Customer lookup', text: 'Invoice, payment and balance history by customer.' },
          ],
          steps: [
            { title: 'Set up', text: 'Numbering, taxes and your company details.' },
            { title: 'Sell', text: 'From the POS, a quote or finance.' },
            { title: 'Issue', text: 'The document is created and sent to your customer.' },
            { title: 'Check', text: 'Status, PDF and payments always at hand.' },
          ],
          highlights: ['Your country’s taxes set up', 'Invoices and credit notes', 'Connected to sales and accounting'],
          faq: [
            { q: 'How does e-invoicing work {inCountry}?', a: '{einvoiceNote}' },
            { q: 'Can I invoice from my phone?', a: 'Yes. Invoicing works in the browser on any device.' },
          ],
        },
      },
    },
    contabilidad: {
      name: 'Accounting and finance',
      short: 'Journal entries, receivables, banks and closings.',
      eyebrow: 'Accounting',
      headline: 'Clear books without retyping.',
      lead: 'Every sale, purchase and payment creates its journal entry. Receivables, payables, banks, reconciliation and closings in the same system where you run your business.',
      pains: [
        { pain: 'Your accountant gets the information late and in scattered files.', answer: 'Automatic journal entries from your operations, ready to review.' },
        { pain: 'You don’t know who owes you or whom you owe.', answer: 'Receivables and payables with installments and reminders.' },
        { pain: 'Bank reconciliation takes days.', answer: 'Reconciliation against transactions imported from your bank.' },
      ],
      features: [
        { title: 'Chart of accounts', text: 'Based on the {chart}, with configurable accounting rules.' },
        { title: 'Automatic journal entries', text: 'Sales, purchases, payments and payroll post themselves.' },
        { title: 'Receivables and payables', text: 'Installments, due dates and payment reminders.' },
        { title: 'Banks and reconciliation', text: 'Bank accounts, transfers and reconciliation.' },
        { title: 'Cost centers and budgets', text: 'Results by location, department or project.' },
        { title: 'Fixed assets and closings', text: 'Depreciation and fiscal periods.' },
      ],
      steps: [
        { title: 'Set up', text: 'Chart of accounts, taxes and accounting rules.' },
        { title: 'Operate', text: 'Every document creates its journal entry.' },
        { title: 'Reconcile', text: 'Match banks, receivables and payments.' },
        { title: 'Close the month', text: 'Review, adjust and lock the period.' },
      ],
      highlights: ['Chart of accounts and accounting rules', 'Bank reconciliation', 'Cost centers and budgets'],
      faq: [
        { q: 'Can my accountant work in GO Admin?', a: 'Yes. You give them a user with the role and permissions they need.' },
        { q: 'What happens if a journal entry fails?', a: 'It’s logged so you can review and fix it, without losing the source document.' },
      ],
    },
    nomina: {
      name: 'Payroll and team',
      short: 'Contracts, shifts and electronic payroll.',
      eyebrow: 'Payroll and team',
      headline: 'Your team, in order.',
      lead: 'Employees, contracts, shifts, attendance, vacation, loans and payroll in one place, connected to accounting.',
      pains: [
        { pain: 'Shifts live in a WhatsApp group.', answer: 'Shift templates and rotations everyone can see.' },
        { pain: 'Running payroll takes a whole day.', answer: 'Pay periods, adjustments and pay stubs calculated for you.' },
        { pain: 'You don’t know how many vacation days each person has left.', answer: 'Vacation and leave balances kept up to date.' },
      ],
      features: [
        { title: 'Employees and contracts', text: 'Positions, departments, salaries and documents.' },
        { title: 'Shifts and rotations', text: 'Templates and assignments by location.' },
        { title: 'Attendance', text: 'Clock-in and clock-out records and timesheets.' },
        { title: 'Vacation and leave', text: 'Requests, approvals and balances.' },
        { title: 'Payroll', text: 'Pay periods, adjustments, pay stubs and electronic payroll with {theAuthority}.' },
        { title: 'Loans and advances', text: 'Installments deducted every period.' },
      ],
      steps: [
        { title: 'Add your team', text: 'Details, contract and salary.' },
        { title: 'Schedule shifts', text: 'Templates and rotations by location.' },
        { title: 'Record changes', text: 'Overtime, absences and vacation.' },
        { title: 'Run payroll', text: 'Pay stubs and journal entries.' },
      ],
      highlights: ['Shifts and attendance', 'Vacation and leave', 'Payroll connected to accounting'],
      faq: [
        { q: 'Can employees see their shifts?', a: 'Yes, with a user and the permissions you set for their position.' },
        { q: 'Does payroll create the journal entries?', a: 'Yes. Every payroll run is posted to accounting.' },
      ],
      variants: {
        noEPayroll: {
          short: 'Contracts, shifts and payroll processing.',
          features: [
            { title: 'Employees and contracts', text: 'Positions, departments, salaries and documents.' },
            { title: 'Shifts and rotations', text: 'Templates and assignments by location.' },
            { title: 'Attendance', text: 'Clock-in and clock-out records and timesheets.' },
            { title: 'Vacation and leave', text: 'Requests, approvals and balances.' },
            { title: 'Payroll', text: 'Pay periods, adjustments and pay stubs under your country’s labor rules.' },
            { title: 'Loans and advances', text: 'Installments deducted every period.' },
          ],
        },
      },
    },

    // -----------------------------------------------------------------------
    // Customers
    // -----------------------------------------------------------------------
    'clientes-crm': {
      name: 'Customers (CRM)',
      short: 'History, opportunities and campaigns.',
      eyebrow: 'Customers & CRM',
      headline: 'Remember every customer.',
      lead: 'Each customer profile brings together purchases, bookings, conversations and tasks. Opportunities in pipelines, follow-ups and campaigns by segment.',
      pains: [
        { pain: 'Customer information lives in one salesperson’s head.', answer: '360° profile with the customer’s full history.' },
        { pain: 'Quotes go cold without follow-up.', answer: 'Pipelines with stages, tasks and reminders.' },
        { pain: 'You send the same promotion to everyone.', answer: 'Segments and campaigns based on what each customer buys.' },
      ],
      features: [
        { title: '360° profile', text: 'Purchases, invoices, bookings, notes and conversations.' },
        { title: 'Sales pipelines', text: 'Custom stages, opportunities and quotes.' },
        { title: 'Tasks and activities', text: 'Calls, meetings and reminders by owner.' },
        { title: 'Segments and campaigns', text: 'By email, WhatsApp or SMS.' },
        { title: 'Automations', text: 'Actions triggered by business events.' },
        { title: 'Consent', text: 'Each customer’s contact preferences.' },
      ],
      steps: [
        { title: 'Bring in your customers', text: 'Import your list or create them as you sell.' },
        { title: 'Organize the pipeline', text: 'Set stages based on how you sell.' },
        { title: 'Follow up', text: 'Tasks and reminders for every opportunity.' },
        { title: 'Reach out', text: 'Campaigns by segment and automations.' },
      ],
      highlights: ['360° profile', 'Pipelines and quotes', 'Campaigns by WhatsApp and email'],
      faq: [
        { q: 'Can I import my current customers?', a: 'Yes, from Excel. They’re also created when you sell or take a booking.' },
        { q: 'Can campaigns go out on WhatsApp?', a: 'Yes, by connecting your WhatsApp Business. Also by email and SMS.' },
      ],
    },
    'chat-omnicanal': {
      name: 'Omnichannel chat',
      short: 'WhatsApp, Instagram and web in one inbox.',
      eyebrow: 'Omnichannel chat',
      headline: 'Every conversation in one inbox.',
      lead: 'WhatsApp, Instagram, Facebook and your website chat all land in the same place. Assign conversations to your team and let an AI assistant answer the common questions.',
      pains: [
        { pain: 'You reply from three different phones.', answer: 'One shared inbox for every channel.' },
        { pain: 'The same questions eat up your day.', answer: 'Quick replies and an AI assistant trained on your information.' },
        { pain: 'You don’t know who helped whom.', answer: 'Assignments, statuses and internal notes on every conversation.' },
      ],
      features: [
        { title: 'Unified inbox', text: 'WhatsApp, Instagram, Facebook and web chat.' },
        { title: 'Assignment and status', text: 'By agent or department, with history.' },
        { title: 'AI assistant', text: 'Answers with your catalog, hours and policies.' },
        { title: 'Quick replies', text: 'Templates for the questions you always get.' },
        { title: 'Website widget', text: 'Chat on your GO Admin website or any other site.' },
        { title: 'Summaries and tags', text: 'Automatic summaries and tags by topic.' },
      ],
      steps: [
        { title: 'Connect your channels', text: 'WhatsApp Business, Instagram and your website.' },
        { title: 'Train the assistant', text: 'With your products, prices and FAQs.' },
        { title: 'Work as a team', text: 'Assign, reply and leave notes.' },
        { title: 'Sell', text: 'The conversation is saved to the customer’s profile.' },
      ],
      highlights: ['WhatsApp, Instagram and web', 'Assistant trained on your information', 'History in the CRM'],
      faq: [
        { q: 'Does the assistant reply on its own?', a: 'It answers common questions with the information you give it; your team can take over the conversation at any time.' },
        { q: 'Do I need WhatsApp Business?', a: 'Yes, to connect WhatsApp to the shared inbox.' },
      ],
    },

    // -----------------------------------------------------------------------
    // Digital channels
    // -----------------------------------------------------------------------
    'sitio-web': {
      name: 'Website',
      short: 'Your site on your own domain, ready in minutes.',
      eyebrow: 'Website',
      headline: 'Your business online from day one.',
      lead: 'Every organization gets its own website on a GO Admin address or its own domain. Pick a template, adjust it to your brand, and it updates itself with your products, services and hours.',
      pains: [
        { pain: 'Having a website meant hiring someone and waiting.', answer: 'Industry templates ready to publish.' },
        { pain: 'Your site falls behind with old prices.', answer: 'Products, prices and hours come straight from the ERP.' },
        { pain: 'Nobody finds you on Google.', answer: 'Title, description and image for search engines and social media on every page.' },
      ],
      features: [
        { title: 'Industry templates', text: 'Modern, classic, elegant, restaurant, hotel, store and parking.' },
        { title: 'Page builder', text: 'Sections you arrange and edit, with drafts and publishing.' },
        { title: 'Your own domain', text: 'A GO Admin subdomain or your own domain, with verification and certificate.' },
        { title: 'Your brand', text: 'Logo, colors, fonts, menus and footer.' },
        { title: 'Search and social', text: 'Metadata, share image and Google verification.' },
        { title: 'Visits and reviews', text: 'Visitor stats and moderated customer reviews.' },
      ],
      steps: [
        { title: 'Pick a template', text: 'Based on your industry.' },
        { title: 'Make it yours', text: 'Logo, colors and content.' },
        { title: 'Connect your domain', text: 'Or use your GO Admin address.' },
        { title: 'Publish', text: 'Your products and hours update themselves.' },
      ],
      highlights: ['Subdomain included, or your own domain', 'Industry templates', 'Content connected to the ERP'],
      faq: [
        { q: 'Can I use my own domain?', a: 'Yes. You connect your domain with a DNS verification; you can also buy one from GO Admin.' },
        { q: 'Do I need to know how to code?', a: 'No. You edit sections, text and images in the builder.' },
        { q: 'What happens if I change a price?', a: 'It updates on your site, because it comes from the same catalog.' },
      ],
    },
    'tienda-en-linea': {
      name: 'Online store',
      short: 'Sell online with your real inventory.',
      eyebrow: 'Online store',
      headline: 'Sell online with the inventory you already have.',
      lead: 'Your catalog published as a store: cart, online payments, delivery or pickup, coupons and reviews. Every order lands in GO Admin, updates stock and is ready to invoice.',
      pains: [
        { pain: 'You track your online store and your inventory separately.', answer: 'The same stock for your physical and online store.' },
        { pain: 'Orders come in by WhatsApp and get lost.', answer: 'Every order has a number, a status and an owner.' },
        { pain: 'Taking payments online seems complicated.', answer: 'Payment gateways from your country, connected.' },
      ],
      features: [
        { title: 'Published catalog', text: 'Categories, variants, photos and prices from inventory.' },
        { title: 'Cart and payments', text: '{gateways} and more.' },
        { title: 'Delivery or pickup', text: 'Shipping rates, free shipping over a set amount and scheduled orders.' },
        { title: 'Coupons and promotions', text: 'Discount codes and countdowns.' },
        { title: 'Real-time orders', text: 'Confirmation, preparation, dispatch and delivery.' },
        { title: 'Customer reviews', text: 'Verified-purchase ratings, with replies.' },
      ],
      steps: [
        { title: 'Turn on the store', text: 'Your catalog is already loaded.' },
        { title: 'Connect payments', text: 'Choose your gateway.' },
        { title: 'Set up delivery', text: 'Delivery, pickup and rates.' },
        { title: 'Receive orders', text: 'They reach the ERP with their status.' },
      ],
      highlights: ['Same inventory as your physical store', 'Online payments {inCountry}', 'Delivery, pickup and coupons'],
      faq: [
        { q: 'Which payment gateways can I use?', a: '{gateways}, among others.' },
        { q: 'Does it work for restaurant orders?', a: 'Yes. With delivery or pickup, tips and scheduled orders.' },
      ],
    },
    'motor-de-reservas': {
      name: 'Booking engine',
      short: 'Direct bookings for rooms, tables and appointments.',
      eyebrow: 'Booking engine',
      headline: 'Direct bookings, with no middleman commissions.',
      lead: 'Your customers book rooms, tables or appointments from your website, with real availability. Bookings land in your GO Admin calendar alongside those from external channels.',
      pains: [
        { pain: 'You depend on platforms that charge a commission on every booking.', answer: 'Direct bookings from your own website.' },
        { pain: 'You confirm bookings one by one over the phone.', answer: 'Automatic confirmation by email or WhatsApp.' },
        { pain: 'Customers don’t show up and you lose the table.', answer: 'Reminders, cancellation policies and deposits.' },
      ],
      features: [
        { title: 'Rooms', text: 'Availability and rates from the PMS, with extras.' },
        { title: 'Tables', text: 'Time slots, party size, areas and table assignment.' },
        { title: 'Appointments and classes', text: 'Scheduling for services, classes and memberships.' },
        { title: 'Deposits and policies', text: 'Prepayments, cancellation and confirmation.' },
        { title: 'Reminders', text: 'By email and WhatsApp before arrival.' },
        { title: 'All in one calendar', text: 'Direct and external-channel bookings, with no overlaps.' },
      ],
      steps: [
        { title: 'Set availability', text: 'Rooms, tables or services.' },
        { title: 'Set rules', text: 'Lead time, groups, deposits.' },
        { title: 'Publish', text: 'On your GO Admin website.' },
        { title: 'Receive', text: 'Confirmed bookings in your calendar.' },
      ],
      highlights: ['Rooms, tables and appointments', 'Deposits and reminders', 'Same calendar as your channels'],
      faq: [
        { q: 'Does it work alongside Booking.com?', a: 'Yes. Direct and channel bookings share the same calendar.' },
        { q: 'Can I ask for a deposit?', a: 'Yes. You decide whether it’s a flat amount or per person.' },
      ],
    },

    // -----------------------------------------------------------------------
    // Insights and AI
    // -----------------------------------------------------------------------
    reportes: {
      name: 'Reports',
      short: 'Dashboards ready for decisions.',
      eyebrow: 'Reports and analytics',
      headline: 'Did you sell more, or earn more?',
      lead: 'Dashboards for sales, margins, receivables, inventory and team, ready from day one. Save your views and get scheduled reports in your inbox.',
      pains: [
        { pain: 'You build reports in Excel at the end of every month.', answer: 'Dashboards that update with every transaction.' },
        { pain: 'You see sales, but not margin.', answer: 'Sales, cost and margin by product and location.' },
        { pain: 'You find out about what matters too late.', answer: 'Alerts when a metric crosses a threshold.' },
      ],
      features: [
        { title: 'Dashboards by area', text: 'Sales, inventory, finance, customers and team.' },
        { title: 'Comparisons', text: 'By period, location, salesperson or channel.' },
        { title: 'Saved reports', text: 'Your filters and columns, ready to run again.' },
        { title: 'Scheduled delivery', text: 'In your inbox every day, week or month.' },
        { title: 'Alerts', text: 'When something needs your attention.' },
        { title: 'Export', text: 'To Excel and PDF.' },
      ],
      steps: [
        { title: 'Open your dashboard', text: 'It comes ready to use.' },
        { title: 'Filter', text: 'By date, location or channel.' },
        { title: 'Save', text: 'Your favorite views.' },
        { title: 'Schedule', text: 'Get the report without asking for it.' },
      ],
      highlights: ['Ready-made dashboards', 'Scheduled reports', 'Alerts by metric'],
      faq: [
        { q: 'Can I see several locations together?', a: 'Yes, and compare them with each other too.' },
        { q: 'Who can see the reports?', a: 'You decide by role: each person sees what’s relevant to them.' },
      ],
    },
    'inteligencia-artificial': {
      name: 'GO Admin AI',
      short: 'Ask your business.',
      eyebrow: 'GO Admin AI',
      headline: 'Ask your business.',
      lead: 'Write the way you’d talk to your accountant. The AI looks at your sales, inventory and receivables and answers with numbers and charts. It also helps you with copy and images for your products.',
      pains: [
        { pain: 'You have data, but no time to analyze it.', answer: 'Questions in plain language, answers with numbers.' },
        { pain: 'Writing product descriptions takes you hours.', answer: 'Copy and images generated from your catalog.' },
        { pain: 'Accounting questions wait for your accountant.', answer: 'An accounting assistant that explains and suggests journal entries.' },
      ],
      features: [
        { title: 'Ask in your own words', text: '“What sold the most this week?” and get the answer.' },
        { title: 'Reports from a question', text: 'With a table and chart ready to share.' },
        { title: 'Accounting assistant', text: 'Explanations and suggestions about your transactions.' },
        { title: 'Product content', text: 'Descriptions and images for your store.' },
        { title: 'Agents that suggest', text: 'Restocking and collection recommendations.' },
        { title: 'Credits by plan', text: '500, 2,000 or 10,000 credits per month, with top-ups.' },
      ],
      steps: [
        { title: 'Open the assistant', text: 'From any screen.' },
        { title: 'Ask', text: 'The way you’d talk to a person.' },
        { title: 'Review', text: 'Numbers, table and chart.' },
        { title: 'Act', text: 'Save the report or create the task.' },
      ],
      highlights: ['Answers from your data', 'Accounting assistant', 'Copy and images for products'],
      faq: [
        { q: 'Can the AI see other businesses’ data?', a: 'No. It only looks at your organization’s information and respects each user’s permissions.' },
        { q: 'What are AI credits?', a: 'Every question or generation uses credits. Each plan includes a monthly amount, and you can buy more.' },
      ],
    },
  },

  solutions: {
    gastronomia: {
      name: 'Restaurants, bars and cafés',
      short: 'Everything that serves food and drinks: tables, bar, counter and delivery.',
      types: [
        'Restaurants',
        'Fast food',
        'Bars and gastropubs',
        'Nightclubs',
        'Coffee shops',
        'Bakeries and pastry shops',
        'Ice cream shops',
        'Food trucks',
        'Dark kitchens',
        'Catering and events',
        'Cafeterias and canteens',
      ],
      headline: 'From order to kitchen, with no paper slips.',
      lead: 'Tables, bar or counter; tickets that reach each station, recipes that deduct ingredients and a register that balances. With an online menu, delivery orders and bookings from your website.',
      pains: [
        { pain: 'Tickets get lost between the bar and the kitchen.', answer: 'Tickets by station, with their status on screen or on the printer.' },
        { pain: 'You don’t know what each dish or drink costs you.', answer: 'Recipes that deduct ingredients and calculate cost.' },
        { pain: 'Orders come in by WhatsApp, apps and phone.', answer: 'Orders from your online store and delivery apps in one place.' },
        { pain: 'Open tabs get tangled at the end of the shift.', answer: 'Checks by table or by person, split at payment.' },
      ],
      day: [
        { moment: 'Before opening', title: 'Check supplies and prep', text: 'Alerts for what’s running low and production orders for the kitchen or bakery.' },
        { moment: 'Rush hour', title: 'Tables, bar and counter', text: 'Fast checkout, split checks, tips and tickets to each station.' },
        { moment: 'All day', title: 'Online orders', text: 'Delivery and pickup orders from your store, with status and owner.' },
        { moment: 'At closing', title: 'Close the day', text: 'Cash count, sales by server or cashier, waste and invoices issued.' },
      ],
      channel: { title: 'Your menu online, with orders and bookings', text: 'Publish your menu with photos, take delivery or pickup orders and table bookings from your website.' },
      features: [
        { title: 'Tables, bar or counter', text: 'Floor plan by area, open tabs or quick sale.' },
        { title: 'Modifiers', text: 'Doneness, add-ons and “no” ingredients on every item.' },
        { title: 'Recipes and production', text: 'Cost per dish or drink, and ingredient deduction.' },
        { title: 'Tips and charges', text: 'Suggested tip, service charge and cover.' },
        { title: 'Multiple registers and stations', text: 'Kitchen, bar, desserts or several points of sale.' },
        { title: 'Waste', text: 'Waste and comps recorded with a reason.' },
        { title: 'Quick buttons', text: 'Your best sellers one tap away.' },
        { title: 'Multiple locations', text: 'Central production and transfers to each location.' },
      ],
      faq: [
        { q: 'Does it work if I don’t have tables, just a counter?', a: 'Yes. You can sell in counter mode, by table or both in the same business.' },
        { q: 'Can I have kitchen tickets on a screen?', a: 'Yes, or on printers by station: kitchen, bar or desserts.' },
        { q: 'Do I get orders from delivery apps?', a: 'There are connectors for delivery apps; check Integrations to see which are available.' },
        { q: 'Can I produce at one location and sell at others?', a: 'Yes, with production orders and transfers between warehouses.' },
      ],
    },
    hospedaje: {
      name: 'Hotels, lodging and tourism',
      short: 'Everything booked by the night or by the day: rooms, cabins and spaces.',
      types: [
        'Hotels',
        'Hostels',
        'Cabins',
        'Glamping',
        'Country houses and vacation homes',
        'Vacation rentals',
        'Motels',
        'Clubs and resorts',
        'Inns and eco-lodges',
        'Travel agencies and tour packages',
      ],
      headline: 'Your property full, with no double bookings.',
      lead: 'Occupancy calendar, check-in and check-out, guest folios, housekeeping and maintenance, and sync with Booking.com, Expedia and Airbnb. With your own booking engine on your website.',
      pains: [
        { pain: 'Overbookings between the portals and the front desk.', answer: 'Availability synced across every channel.' },
        { pain: 'You pay a commission on almost every booking.', answer: 'A direct booking engine on your own website.' },
        { pain: 'Guest charges are forgotten at checkout.', answer: 'Folios with charges from the restaurant, minibar and services.' },
        { pain: 'Bookings arrive by WhatsApp and get written in a notebook.', answer: 'One calendar, with deposits and confirmation.' },
      ],
      day: [
        { moment: 'In the morning', title: 'Check arrivals and departures', text: 'Housekeeping knows which room, cabin or space to prepare.' },
        { moment: 'Midday', title: 'Check-out', text: 'Folio closed and invoice sent to the guest.' },
        { moment: 'In the afternoon', title: 'Check-in', text: 'Guest registration and space assignment.' },
        { moment: 'At night', title: 'New bookings', text: 'They arrive from the portals and your website in the same calendar.' },
      ],
      channel: { title: 'Direct booking engine', text: 'Your website with photos, rates and real availability, so guests can book and pay the deposit with no middleman.' },
      features: [
        { title: 'Occupancy calendar', text: 'By room type, cabin or space, with blocks.' },
        { title: 'Portal sync', text: 'Booking.com, Expedia, Airbnb and iCal.' },
        { title: 'Flexible rates', text: 'By season, night, day or number of guests.' },
        { title: 'Housekeeping and maintenance', text: 'Tasks prioritized by arrival and departure.' },
        { title: 'Folios and charges', text: 'Restaurant, minibar and services charged to the account.' },
        { title: 'Groups and companies', text: 'Group bookings, packages and corporate accounts.' },
        { title: 'Online deposits', text: 'Payments through the integrated gateways.' },
        { title: 'Repeat guests', text: 'History, preferences and communication.' },
      ],
      faq: [
        { q: 'Does it work for cabins, glamping or country houses?', a: 'Yes. You set up your spaces, types, capacity and rates to match how you operate, whether they’re rooms or standalone units.' },
        { q: 'What if I also have a restaurant or a pool and spa area?', a: 'Charges are rung up at the point of sale and added to the guest’s folio.' },
        { q: 'Can I collect deposits?', a: 'Yes, from the booking engine with online payments.' },
      ],
    },
    'espacios-y-eventos': {
      name: 'Venues, courts and events',
      short: 'Everything booked by the hour: courts, event halls, clubs and activities.',
      types: [
        'Turf fields and courts',
        'Social and sports clubs',
        'Event venues',
        'Coworking spaces and meeting rooms',
        'Recreation parks',
        'Pools and recreation centers',
        'Escape rooms',
        'Recording and photo studios',
        'Tours and experiences',
      ],
      headline: 'Your spaces booked, with no overlaps.',
      lead: 'Bookings by the hour or by the day, online deposits, tickets and purchases in one place. Your customers see real availability on your website and book on their own.',
      pains: [
        { pain: 'Two groups show up at the same court at the same time.', answer: 'A calendar for each space, with real availability.' },
        { pain: 'No-shows leave the space empty.', answer: 'Online deposits and automatic confirmation.' },
        { pain: 'The café, rentals and tickets are charged separately.', answer: 'Everything at the same register and in the same report.' },
      ],
      day: [
        { moment: 'In the morning', title: 'Check the schedule', text: 'Spaces booked, deposits received and what’s still to be collected.' },
        { moment: 'All day', title: 'Bookings from your website', text: 'Your customers choose the space, date and time, and pay the deposit.' },
        { moment: 'During use', title: 'Purchases and tickets', text: 'Drinks, equipment rental and tickets at the point of sale.' },
        { moment: 'At closing', title: 'Closing', text: 'Occupancy by space, sales and invoices.' },
      ],
      channel: { title: 'Online space booking', text: 'Your customers book a court, hall or activity by the hour from your website and pay the deposit.' },
      features: [
        { title: 'Hourly bookings', text: 'Time blocks per space, with a minimum duration.' },
        { title: 'Rates by time slot', text: 'Different prices at peak hours, on weekends or holidays.' },
        { title: 'Deposits and prepayments', text: 'Online payments when booking.' },
        { title: 'On-site purchases', text: 'Café, equipment rental and tickets.' },
      ],
      faq: [
        { q: 'Can I have several courts or halls?', a: 'Yes. Each space has its own calendar, capacity and rate.' },
        { q: 'Does it work for member clubs?', a: 'Yes. Members are registered as customers, and you can combine bookings with memberships from Gyms, academies and memberships.' },
      ],
    },
    comercio: {
      name: 'Stores and retail',
      short: 'Everything that sells products: in store, online or wholesale.',
      types: [
        'Convenience stores and supermarkets',
        'Clothing, footwear and accessories',
        'Hardware stores',
        'Drugstores',
        'Electronics and phones',
        'Stationery and bookstores',
        'Pet stores',
        'Cosmetics and beauty',
        'Furniture and home decor',
        'Distributors and wholesalers',
        'Online-only stores',
      ],
      headline: 'Sell in store and online with one inventory.',
      lead: 'Point of sale with barcodes, variants, price lists, inventory by location, a connected online store and invoicing from the same sale.',
      pains: [
        { pain: 'You sell something online that’s no longer in the store.', answer: 'One inventory for your physical and online store.' },
        { pain: 'Managing sizes, colors or pack sizes is chaos.', answer: 'Variants with their own stock and barcode.' },
        { pain: 'You don’t know which products move and which sit on the shelf.', answer: 'Turnover and margin reports by product.' },
        { pain: 'Your wholesale customers pay different prices.', answer: 'Price lists and credit by customer.' },
      ],
      day: [
        { moment: 'At opening', title: 'Check stock', text: 'Stock by location and reorder alerts.' },
        { moment: 'During the day', title: 'Sell at the counter', text: 'Barcodes, split payments and invoices.' },
        { moment: 'In the afternoon', title: 'Online orders come in', text: 'Pick, ship and invoice.' },
        { moment: 'At closing', title: 'Closing and purchasing', text: 'Sales by salesperson and channel, and orders to suppliers.' },
      ],
      channel: { title: 'Your online store, ready to go', text: 'Your catalog published with cart, payments, shipping and coupons, connected to the same inventory.' },
      features: [
        { title: 'Variants', text: 'Sizes, colors, pack sizes and SKUs.' },
        { title: 'Barcodes', text: 'For sales, purchases and counts.' },
        { title: 'Price lists', text: 'Retail, wholesale or by customer.' },
        { title: 'Multi-location', text: 'Inventory and prices by branch.' },
        { title: 'Purchasing and suppliers', text: 'Purchase orders and receiving.' },
        { title: 'Batches and expiration dates', text: 'For food, medicine and cosmetics.' },
        { title: 'Promotions', text: 'Discounts, coupons and seasonal sales.' },
        { title: 'Warranties', text: 'Serial numbers and claims.' },
      ],
      faq: [
        { q: 'Can I use a barcode scanner?', a: 'Yes, at the point of sale, in purchasing and in counts.' },
        { q: 'Does it work for wholesale?', a: 'Yes: price lists, quotes, credit and receivables by customer.' },
        { q: 'Can I sell only online, without a physical store?', a: 'Yes. The online store works on its own, with the same inventory and invoicing.' },
      ],
    },
    'belleza-y-salud': {
      name: 'Beauty, health and wellness',
      short: 'Everything that runs on appointments: services, professionals and schedules.',
      types: [
        'Hair salons and barbershops',
        'Spas and aesthetic centers',
        'Nails and lashes',
        'Medical offices',
        'Dental clinics',
        'Physical therapy',
        'Psychology and therapy',
        'Veterinary clinics',
        'Opticians',
        'Tattoo studios',
      ],
      headline: 'A full schedule, and customers who come back.',
      lead: 'Appointments by professional, reminders, each client’s history, services and products at the same register, and a website where your clients book on their own.',
      pains: [
        { pain: 'Appointments are booked over WhatsApp and overlap.', answer: 'Schedule by professional and by service, with no overlaps.' },
        { pain: 'Clients who don’t show up for their appointment.', answer: 'Automatic reminders and an optional deposit.' },
        { pain: 'You don’t know how much each professional sells.', answer: 'Sales and services by professional in your reports.' },
      ],
      day: [
        { moment: 'At opening', title: 'Check the schedule', text: 'Today’s appointments by professional and by room.' },
        { moment: 'During the day', title: 'Serve and get paid', text: 'Services and products on the same check, with an invoice.' },
        { moment: 'All day', title: 'New online appointments', text: 'Your clients choose the service, professional and time.' },
        { moment: 'At closing', title: 'Follow-up', text: 'Sales by professional and clients to reach out to again.' },
      ],
      channel: { title: 'Appointment booking on your website', text: 'Your clients choose the service, the professional and the time, and get a confirmation.' },
      features: [
        { title: 'Schedule by professional', text: 'Hours, services and rooms for each person.' },
        { title: 'Reminders', text: 'By email or WhatsApp before every appointment.' },
        { title: 'Client history', text: 'Services, purchases and notes from every visit.' },
        { title: 'Services and products', text: 'On the same check, with supplies inventory.' },
      ],
      faq: [
        { q: 'Can my clients book on their own?', a: 'Yes, from your website, choosing the service, professional and an available time.' },
        { q: 'Can I sell session packages?', a: 'Yes, as products or plans the client uses over several visits.' },
      ],
    },
    'gimnasios-y-academias': {
      name: 'Gyms, academies and memberships',
      short: 'Everything that sells plans: members, classes, access and renewals.',
      types: [
        'Gyms',
        'Functional training',
        'Yoga, Pilates and dance',
        'Language schools and courses',
        'Sports schools',
        'Member clubs',
        'Martial arts',
        'Swim centers',
      ],
      headline: 'Memberships up to date, classes full.',
      lead: 'Membership plans, freezes, QR access control, classes with capacity limits and bookings, and recurring billing. With your own website to sell plans and book classes.',
      pains: [
        { pain: 'Members getting in with an expired membership.', answer: 'Access checked against membership status.' },
        { pain: 'Classes get overbooked or stay empty.', answer: 'Spots and bookings from the phone.' },
        { pain: 'Collecting monthly fees means chasing people.', answer: 'Reminders and online payments.' },
      ],
      day: [
        { moment: 'At opening', title: 'Check-ins', text: 'QR check-in and expiration alerts.' },
        { moment: 'During the day', title: 'Classes', text: 'Attendance for those who booked.' },
        { moment: 'Midday', title: 'Sales', text: 'Plans, products and renewals.' },
        { moment: 'At closing', title: 'Follow-up', text: 'Members about to expire and inactive members.' },
      ],
      channel: { title: 'Class booking and plan sales', text: 'Your members and students book classes and renew their plan from your website.' },
      features: [
        { title: 'Plans and memberships', text: 'Monthly, quarterly, annual or by session.' },
        { title: 'Freezes', text: 'Pauses with a reactivation date.' },
        { title: 'QR access', text: 'Check-in and access devices.' },
        { title: 'Classes and spots', text: 'Schedules, instructors and bookings.' },
      ],
      faq: [
        { q: 'Does it work for academies or courses, not just gyms?', a: 'Yes. Courses are managed as plans with schedules, spots and attendance.' },
        { q: 'Can I charge for single sessions?', a: 'Yes. You can sell plans by number of sessions or single passes.' },
      ],
    },
    movilidad: {
      name: 'Parking, transportation and mobility',
      short: 'Everything that moves or stores vehicles: spaces, routes, tickets and shipments.',
      types: [
        'Parking lots',
        'Car washes',
        'Passenger transportation',
        'Charter and tour transportation',
        'Parcel and courier services',
        'Vehicle rentals',
        'Auto repair and service shops',
      ],
      headline: 'Every vehicle, every minute, charged.',
      lead: 'Entries and exits by license plate with time-based rates, monthly passes, routes and tickets with seat selection, shipments with tracking numbers, fleet and drivers, all synced with the register and invoicing.',
      pains: [
        { pain: 'Paper tickets that get lost.', answer: 'Entry recorded by license plate, with a printed or digital ticket.' },
        { pain: 'Miscalculated charges at exit.', answer: 'Rates by the minute, hour or day applied automatically.' },
        { pain: 'Seats oversold on the same trip.', answer: 'Seat assignment per trip.' },
        { pain: 'Fleet documents expiring.', answer: 'Vehicles and licenses with alerts.' },
      ],
      day: [
        { moment: 'At opening', title: 'Start the shift', text: 'Register, starting occupancy and the day’s dispatches.' },
        { moment: 'Rush hour', title: 'Entries and sales', text: 'Check-in by license plate, tickets at the counter and online.' },
        { moment: 'In the afternoon', title: 'Shipments and departures', text: 'Waybills, deliveries and calculated charges.' },
        { moment: 'At closing', title: 'End of shift', text: 'Cash count, occupancy and revenue by route or operator.' },
      ],
      channel: { title: 'Rates, monthly passes and tickets online', text: 'Publish rates, hours and location; sell monthly passes or tickets with seat selection from your website.' },
      features: [
        { title: 'Space map', text: 'Zones and vehicle types.' },
        { title: 'Time-based rates', text: 'By the minute, hour, day or fraction.' },
        { title: 'Monthly passes', text: 'Subscriptions with authorized vehicles.' },
        { title: 'Routes and tickets', text: 'Schedules, stops and seat map.' },
        { title: 'Shipments', text: 'Waybills, manifests and proof of delivery.' },
        { title: 'Fleet', text: 'Vehicles, drivers and incidents.' },
        { title: 'Shifts', text: 'Closing by operator.' },
        { title: 'Vehicle services', text: 'Washing, parking and services on the same account.' },
      ],
      faq: [
        { q: 'Can I have different rates by vehicle?', a: 'Yes, by vehicle type and time of day.' },
        { q: 'Do you handle parcels?', a: 'Yes: waybills, manifests, delivery attempts and proof of delivery.' },
      ],
    },
    servicios: {
      name: 'Services and businesses',
      short: 'Everything that sells expertise or work: projects, quotes and billing.',
      types: [
        'Agencies and consulting firms',
        'Accountants and lawyers',
        'Construction and maintenance',
        'Repair shops and technical service',
        'Education and schools',
        'Software companies',
        'Real estate agencies',
        'Security and cleaning services',
        'Foundations and nonprofits',
      ],
      headline: 'From first contact to final payment.',
      lead: 'Opportunities, quotes, scheduling, projects with tasks and hours, invoicing, accounting and receivables, all in one place.',
      pains: [
        { pain: 'You write quotes in Word and lose track of follow-ups.', answer: 'Quotes linked to your sales pipeline.' },
        { pain: 'You don’t know if a project is profitable.', answer: 'Hours and costs by project.' },
        { pain: 'Receivables pile up.', answer: 'Installments and payment reminders.' },
      ],
      day: [
        { moment: 'In the morning', title: 'Today’s schedule', text: 'Appointments, tasks and meetings.' },
        { moment: 'Midday', title: 'Send quotes', text: 'From the opportunity, with follow-up.' },
        { moment: 'In the afternoon', title: 'Deliver', text: 'Projects, milestones and hours logged.' },
        { moment: 'At closing', title: 'Get paid', text: 'Invoice and automatic reminder.' },
      ],
      channel: { title: 'Website with scheduling and a contact form', text: 'Showcase your services, receive requests and let your clients book appointments.' },
      features: [
        { title: 'Quotes', text: 'With templates and approval.' },
        { title: 'Projects', text: 'Milestones, tasks and team.' },
        { title: 'Hours', text: 'Time tracking by task.' },
        { title: 'Receivables', text: 'Installments and reminders.' },
      ],
      faq: [
        { q: 'Does it work for businesses with recurring billing?', a: 'Yes: plans, subscriptions and recurring invoicing.' },
        { q: 'Can my accountant log in?', a: 'Yes, with a role that only sees accounting and reports.' },
      ],
    },
  },

  integrations: {
    groups: {
      pagos: {
        name: 'Payments and banks',
        text: 'Get paid online, by QR or with a card terminal, and reconcile your accounts.',
        items: {
          'Wompi': 'Online payments.',
          'PSE': 'Direct debit from bank accounts.',
          'Nequi': 'Digital wallet payments.',
          'DaviPlata': 'Digital wallet payments.',
          'SPEI': 'Instant transfers.',
          'OXXO Pay': 'Cash payments in store.',
          'Conekta': 'Cards and online payments.',
          'PayU': 'Cards and local payment methods.',
          'Mercado Pago': 'Online and QR payments.',
          'Bold': 'Card terminals and payment links.',
          'Bre-B': 'Instant payments from Banco de la República.',
          'Bancolombia': 'Accounts and transactions.',
          'Redeban': 'Card terminals and acquiring.',
          'Stripe': 'International payments.',
          'PayPal': 'International payments.',
          'Venmo': 'Person-to-person payments.',
          'Cash App': 'Person-to-person payments.',
          'Zelle': 'Bank transfers.',
        },
      },
      reservas: {
        name: 'Booking channels',
        text: 'Availability and bookings synced with your calendar.',
        items: {
          'Booking.com': 'Bookings, rates and availability.',
          'Expedia Group': 'Bookings and availability.',
          'Airbnb': 'Calendar and bookings.',
          'Google Vacation Rentals': 'Presence on Google.',
          'TripAdvisor': 'Presence and reviews.',
        },
      },
      domicilios: {
        name: 'Delivery and shipping',
        text: 'Orders from apps and carrier shipping labels.',
        items: {
          'Rappi': 'Delivery orders.',
          'Uber Eats': 'Delivery orders.',
          'iFood': 'Delivery orders.',
          'Coordinadora': 'Shipping labels and tracking.',
          'Servientrega': 'Shipping labels and tracking.',
          'Interrapidísimo': 'Shipping labels and tracking.',
          'Envía': 'Shipping quotes and labels.',
        },
      },
      mensajeria: {
        name: 'Messaging',
        text: 'Chat with your customers and keep them informed.',
        items: {
          'WhatsApp Business': 'Chat, campaigns and notifications.',
          'Twilio': 'SMS and calls.',
          'SendGrid': 'Transactional email.',
        },
      },
      marketing: {
        name: 'Social and advertising',
        text: 'Catalog, messages and campaigns.',
        items: {
          'Meta (Facebook, Instagram)': 'Messages and catalog.',
          'TikTok Business': 'Catalog and campaigns.',
          'Google Ads': 'Conversions and campaigns.',
        },
      },
    },
    developer: [
      { title: 'API', text: 'Read and create your organization’s data with access keys.' },
      { title: 'Webhooks', text: 'Get events when something happens: a sale, a booking, a payment.' },
      { title: 'Syncs', text: 'Scheduled jobs with a log of every run.' },
    ],
  },
}
